### ISSUE TITLE
Add link to Java repository

### ISSUE THREAD

**Issue by iluwatar** [30-seconds/30-seconds-of-code#1004]
Hi there! Inspired by this repository I've been working on Java version of it. It's called 30-seconds-of-java and is available here https://github.com/iluwatar/30-seconds-of-java. Would it be possible to add a link to your `README.md` pointing to this repository? Thanks.

**Comment by iluwatar** [comment]
By the way, how have you implemented the web site? Is there any documentation I could refer to when setting up my own?

**Comment by fejes713** [comment]
Hey @iluwatar 

It's nice to hear that you were inspired by our work :) Kudos for making the Java version of it! 

> Would it be possible to add a link to your README.md pointing to this repository?

As far as I know, there're few Java-specific versions of original `30-seconds-of-code`. I think it'd be a bit unfair to link one over the another but we'll definitely find a way to do so in the next iteration of the website which is hopefully coming very soon.

Speaking of the website, you can see the list of builder scripts under `package.json` file. The current version is built using [Hyperapp](https://hyperapp.dev/) but we're making some big changes in the next few months. The first image in `CONTRIBUTING.md` might give you a better sense of what is happening under the hood. 

The next version of the website is going to be based on our [starter kit](https://github.com/30-seconds/30-seconds-starter). It runs Gatsby and should perform much better than the current implementation. Apart from performance increase, it'll simplify the whole process for contributors so I highly suggest you look that one up. 

Looking forward to your repo! Let me know here if you need something else 😄

**Comment by razinda8** [comment]
Branches:Master/Rizanda8/Hello World/ 
Add link to java repository #1004

**Comment by Chalarangelo** [comment]
The suggested project hasn't managed to get enough content and/or traffic in the meantime. We are not currently interested in acquiring this asset as part of the organization. However, we will contact you shall we ever decide to move forward with integrating a Java repository into our websites.
