### ISSUE TITLE
deepClone convert null to plain object

### ISSUE THREAD

**Issue by carlos-montiers** [30-seconds/30-seconds-of-code#1008]
## Bug description 
If you clone an object that have properties with null value, the cloned object have the property with a plain object as value.

## Steps to reproduce
```
let obj = {a: null};

let cloned = deepClone(obj);

console.log(cloned)

// {a: {}}
```

## Expected behavior
`// {a: null}`

**Comment by Chalarangelo** [comment]
Resolved in #1010
