### ISSUE TITLE
deepClone loses prototype.constructor

### ISSUE THREAD

**Issue by carlos-montiers** [30-seconds/30-seconds-of-code#1009]
## Bug description 
If you clone an object that have prototype constructor from a class, the cloned object have Object as the prototype constructor instead of the class.

## Steps to reproduce
```
class A {
    myMethod() {
        return true;
    }
}

let obj = new A();
let cloned = deepClone(obj);

console.log(obj.constructor);
// class A

console.log(cloned.constructor);
// ƒ Object()
```

## Expected behavior
```
console.log(cloned.constructor);
// class A
```

**Comment by Chalarangelo** [comment]
This is correct functionality. ES6 classes, when cloned, default to the `Object` prototype. If you want to clone a class instance, `deepClone` should not be used, and you should instead use a different method, such as `Object.create()`. I will see if we should add notes about this and/or an extra snippet for that case.
