### ISSUE TITLE
[Suggestion] Revert example &  snippet

### ISSUE THREAD

**Issue by luvsunlight** [30-seconds/30-seconds-of-code#1038]
[Suggestion]. It would better if revert example and snippet just like another repo "30-seconds-of CSS".

Like this =>

**ary**
Creates a function that accepts up to n arguments, ignoring any additional arguments.

Call the provided function, fn, with up to n arguments, using Array.prototype.slice(0,n) and the spread operator (...).

eg. 
> const firstTwoMax = ary(Math.max, 2);
[[2, 6, 'a'], [6, 4, 8], [10]].map(x => firstTwoMax(...x)); // [6, 6, 10]

<details>
<summary>Snippet</summary>

> const ary = (fn, n) => (...args) => fn(...args.slice(0, n));

</details>

**Comment by Chalarangelo** [comment]
Thanks for the suggestion. However, most of our userbase indicate the opposite, actually. It is a more common use-case to want a snippet that does something and copy it to use in your project than the opposite.
