### ISSUE TITLE
objectToQueryString

### ISSUE THREAD

**Issue by WoodsLiu** [30-seconds/30-seconds-of-code#1043]
Thank you very much for this open source project, I learned a lot, I saw this problem today when I was studying the code.
If the first property value passed into the object is not a string, it is not the desired result.
for example:
```javascript
objectToQueryString({ value: undefined, page: '1', size: '2kg', key: undefined })
// => &page=1&size=2kg
```
I implemented this myself, which is not optimal code, but it's the cleanest code I can think of right now.
```javascript
const objectToQueryString = queryParams =>
   queryParams ? '?' + Object.entries(queryParams)
	        .filter(([key,val]) => typeof val === 'string')
		.map(v => v.join('=')).join('&') : ''
```
Hope to improve this method

**Comment by kanhaiyaagrawal01** [comment]
Hey @WoodsLiu, I would like to help improve this. Can you please help me with more details

**Comment by WoodsLiu** [comment]
oh, as described before, If the first property value passed into the object is not a string, it is not the desired result.
for example:
If the first propery value passed into the object is `null`、`undefined` or `NaN`
```javascript
objectToQueryString({ value: null, page: '1', size: '2kg' });
objectToQueryString({ value: undefined, page: '1', size: '2kg' });
objectToQueryString({ value: NaN, page: '1', size: '2kg' });
```
They're all the same answer: `&page=1&size=2kg`, but I think the correct answer should be  
`?page=1&size=2kg`, I think this method should omit false values such as `NaN`, `undefined` and `null` when converting an object to a string.  

But there is a special case:
if the first propery value passed into the object is a `false` or number `0`, ok, this is `false` value, but I don't think it can be filtered.
```javascript
objectToQueryString({ value:0, page: '1', size: '2kg', key: undefined })
objectToQueryString({ value:false, page: '1', size: '2kg', key: undefined })
// => &page=1&size=2kg
// => &page=1&size=2kg
```
So their answer shouled be `?value=0&page=1&size=2kg` and `?value=false&page=1&size=2kg`.

other cases:
```javascript
objectToQueryString({ value:true, page: '1', size: '2kg', key: undefined })
// correct answer: ?value=true&page=1size=2kg
objectToQueryString({ value:1, page: '1', size: '2kg', key: undefined })
// correct answer: ?value=1&page=1size=2kg
```

Finally, I think this method should filter out the false values, but not the Boolean value `false`, the value `0`, this method only filters part of it(the previous example only omitted `key:undefined`), and that's where it needs to perfected. So here are some of my thoughts on this approach.

**Comment by IMHOJEONG** [comment]
I think this method is fine.
```javascript
const objectToQueryString = queryParams =>
   queryParams ? '?' + Object.entries(queryParams)
	        .filter(([key,val]) => ![undefined,null,NaN].includes(val))
		.map(v => v.join('=')).join('&') : ''
```

**Comment by skatcat31** [comment]
I'm not certain it matters that there is an undefined or null or nan in there as long as we coerce it to a proper string. A query parameter being empty is as good as an empty query parameter so I'm not certain it's such a problem. I think we only want to solve that if a value is empty, we get an empty key

**Comment by cookch10** [comment]
What about nested object attributes and arrays?  Can this be reversed to construct the same object back from the generated query string?
