### ISSUE TITLE
merge maps

### ISSUE THREAD

**Issue by mikeal** [30-seconds/30-seconds-of-code#1051]
I ended up writing this one today. Not sure where it would belong in the snippets but it’s quite useful as it merges Maps without suffering full copies like most of the examples you tend to find.

```javascript
const allEntries = function * (maps) {
  for (const map of maps) {
    yield * map
  }
}
const mergeMaps = maps => new Map(allEntries(maps))
```

**Comment by Chalarangelo** [comment]
This could be PRed, but I think it's a bit too advanced for the scope of the repo, maybe when we start a blog (finally), it could be a short article that explains everything behind it?

**Comment by mikeal** [comment]
Sure, I’d be down to write that up. Ping me once you have the blog setup ;)
