### ISSUE TITLE
Add 30-seconds-of-Julia

### ISSUE THREAD

**Issue by logankilpatrick** [30-seconds/30-seconds-of-code#1056]
Hey all, 

It would be awesome to spin up a 30 seconds of Julia repo. Happy to take the lead on this. 

Julia has been downloaded over 10 million times and the popularity is increasing significantly over time. 

www.julialang.org

https://docs.julialang.org/en/v1/

**Comment by travelingBug** [comment]
nice !the luck with 30-second! 发自我的华为手机-------- 原始邮件 --------发件人： Logan Kilpatrick <notifications@github.com>日期： 2019年12月12日周四 晚上10:36收件人： 30-seconds/30-seconds-of-code <30-seconds-of-code@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [30-seconds/30-seconds-of-code] Add 30-seconds-of-Julia (#1056)Hey all,
It would be awesome to spin up a 30 seconds of Julia repo. Happy to take the lead on this.
Julia has been downloaded over 10 million times and the popularity is increasing significantly over time.
www.julialang.org
https://docs.julialang.org/en/v1/

**Comment by Chalarangelo** [comment]
We are currently looking into new languages to add to the organization, as we have recently created proper tools to integrate new content repositories much faster. New repositories should be created inside the organization, so we can properly curate and update them. However, we currently lack the technical knowledge in this specific language.

If we decide to move forward with this, I would like to know the following things:
1. Can you, with absolute certainty, commit to working weekly for the next 6-12 months to add and curate content in such a repository to keep the quality standards we have set in other repositories?
2. Do you feel like you have enough knowledge to undertake such a task?
3. Are you prepared to join the organization and help out with the maintenance of such a repository and also participate in meta discussions we might have about the future of this and other projects?
4. Do you have enough content to kickstart this project (i.e. 20-25 snippets) or are you certain that you can provide such content?
5. Do you solemnly swear to be nice and polite to people and handle community interactions properly?

I know it sounds like a ton to ask, but we really need someone to take it upon themselves to maintain such a repo, as we lack the knowledge to do so ourselves right now. If you can respond to all of the above with a mostly positive answer, we will consider this and get back to you.

**Comment by logankilpatrick** [comment]
I will be able to help out until October of 2020! I have been using Julia at NASA since October 2017 and am currently helping out with multiple Julia open-source projects + Interning with Julia Computing on the PumasAI project. 

Happy to help with maintenance and I can make 20-25 snippets. 

Helping people and being nice is half the fun! 

So, yes, yes, yes, yes, and yes! Let me know how you want to proceed further. I am sure I can also get others to help on this front since I alone don't possess all of the relevant knowledge that should be passed on.

**Comment by Chalarangelo** [comment]
@logankilpatrick We'll get back to you very very soon, hang on tight!

**Comment by logankilpatrick** [comment]
any update on this?

**Comment by Chalarangelo** [comment]
@logankilpatrick I will start doing the necessary work to start such a repository in an hour or two:

- Create a repository under the organization.
- Set up the repository properly.
- Set up the repo's snippet template.
- Create a team under the organization.
- Invite you to the organization.

After that point, you will be able to contribute snippets. You will most likely have read access to the repository for a while, to make sure everything goes smoothly and I will take the time to review structure and content only as necessary to check that the setup is done right.

Remember to make each snippet a function that follows the template (very much similar to the way 30s JS snippets work). PR each snippet on its own, unless they are thematically linked (isEven and isOdd in one PR makes sense for example). After the repo reaches 50+ snippets, we will look into website integration.

**Comment by Chalarangelo** [comment]
@logankilpatrick Welcome aboard! Start working on PRs and stuff and I will review them as soon as I have time. :tada: :tada: :tada: :tada: :tada:

**Comment by logankilpatrick** [comment]
Awesome. What is the general Consensus on porting examples between language? Is that encouraged?

**Comment by Chalarangelo** [comment]
@logankilpatrick Mostly, yes. The only issue would be snippets that are already implemented in the language natively (e.g. if isEven exists in Julia, don't port it). It's usually the first place we start looking for snippets and it's also easier to set up properly. Remember to follow the best practice and naming rules of your language to minimize review work and necessary changes.

**Comment by logankilpatrick** [comment]
Okay, awesome. I am traveling all day today and wrapping up finals but I will try to get some PR's open later this week. Thanks again!!

**Comment by Savagelife5150** [comment]
Unsubscrine

**Comment by Savagelife5150** [comment]
Unsubscribe

**Comment by kpotter83** [comment]
> On Dec 18, 2019, at 7:30 PM, Savagelife5150 <notifications@github.com> wrote:
> 

﻿
Unsubscribe
