### ISSUE TITLE
BOT Spam

### ISSUE THREAD

**Issue by seanzamora** [30-seconds/30-seconds-of-code#1059]
## Description

To start off keep up the great work sharing all these helpful snippets with the community, much appreciated.

It appears the lock[bot] is mass spamming everyone's email. Can you please disable the notification so we don't get bombarded with emails. Thanks in advance.

**Comment by Chalarangelo** [comment]
Uhm, I think the notification setting is based on personal preference instead of repository setting - correct me if I am wrong. We are really sorry about this, it should stop very soon when it processes everything.

**Comment by Chalarangelo** [comment]
Just muted the lock[bot], should be ok now. Sorry for the inconvenience.
