### ISSUE TITLE
Alternative way to check equality for allEqual

### ISSUE THREAD

**Issue by justchen1369** [30-seconds/30-seconds-of-code#1060]
There is an alternative way to check equality for `allEqual`: 

```js
const allEqual = arr => [...new Set(arr)].length > 0;
```

**Comment by kpotter83** [comment]
STOP FUCKING EMAILING ME! 

> On Dec 18, 2019, at 8:33 PM, request-info[bot] <notifications@github.com> wrote:
> 

﻿
We would appreciate it if you could provide us with some more information about this issue/PR!

**Comment by Chalarangelo** [comment]
This seems like a valid option, I will perf this in a bit and see if it is any better.

**Comment by Chalarangelo** [comment]
Based on [this benchmark](http://jsben.ch/rTzBA) the existing implementation is faster apart from being easier to read. Closing on that basis.
