### ISSUE TITLE
getScrollPosition | Wrong properties choices

### ISSUE THREAD

**Issue by remylenoir** [30-seconds/30-seconds-of-code#1080]
## Bug description 
Wrong properties choices of `scrollLeft` and `scrollTop` in the ternary operator.

The Window object does not have these properties, see [Window - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window).
The Element object does,  see [Element - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft).

```js
const getScrollPosition = (el = window) => ({
  x: el.pageXOffset !== undefined ? el.pageXOffset : el.scrollLeft,
  y: el.pageYOffset !== undefined ? el.pageYOffset : el.scrollTop
});
```

**Comment by Chalarangelo** [comment]
I am not entirely certain of the original intention here, but as far as I can tell, the ternary implies that it will use `pageXOffset` and `pageYOffset` if available, which they are for `window` instead of `scrollLeft` and `scrollTop`. Therefore, I think the choice here is intentional to accept either the window or an element.

**Comment by remylenoir** [comment]
I see, my assumption was that the computed element would always be the `window`.

In the context of a project with TypeScript and TSLint, if the intention is to compute the `window`, the ternary alternative options would not be valid, because these options will be tested. And then we are back on my initial message above (with invalid properties for the Window object).

I understand that is 30 sec of JS without TypeScript, but as a suggestion, maybe it would be better to have a more specific example to avoid any confusion:
- one code block to get the scroll position from the `window`
- another one to get the scroll position from any other element

Thank you for your quick answer.

**Comment by Chalarangelo** [comment]
@remylenoir We're currently revising a lot of the code and examples, making sure everything is up to date and high quality, so we will take a look sooner or later. Thanks for the feedback!
