### ISSUE TITLE
Update explanation for mapObject

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-code#1092]
[mapObject](https://www.30secondsofcode.org/js/s/map-object/)'s explanation is not up to standards with our current format. It should be updated to match the rest of the snippets.

We could also make the example a one-liner.

**Comment by ezracelli** [comment]
Perhaps a simpler implementation:

```js
const mapObject = (arr, fn) => Object.assign(...arr.map(el => ({ [el]: fn(el) })))
```

**Comment by floods-technology** [comment]
https://github.com/30-seconds/30-seconds-of-code/issues/1092#issuecomment-596132421

**Comment by icncsx** [comment]
@ezracelli did you make a PR?
