### ISSUE TITLE
🐛 JS toCamelCase case with SOME_UPPER_SNAKE_CASE

### ISSUE THREAD

**Issue by ashmna** [30-seconds/30-seconds-of-code#1093]
## Bug description 
JS toCamelCase case with 'SOME_UPPER_SNAKE_CASE'

## Expected behavior
convert to 'someUpperSnakeCase'

**Comment by ashmna** [comment]
I have a working solution

just change regex from `/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g` to `/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b|[_])|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g`

Not sure that it is a good solution

**Comment by Chalarangelo** [comment]
Thanks for pointing this one out!

The regex might work but is still ridiculously long, we should either decide if this is a `wontfix` or actually find a shorter one that makes sense.

**Comment by ashmna** [comment]
Sure regex is long but it has educational value,
and there is can't be any compromise ;) in my option, the function must do his work correctly, I mean no one has to convert the string before calling such useful function

**Comment by Chalarangelo** [comment]
We usually try to strike a balance between common use-cases and brevity, such a regexp is impossible to use in the current format as it's not understandable in 30 seconds (or even 5 minutes) or less. I suggest we add a disclaimer about the string needing to be converted in such a case and I might write a blog later.
