### ISSUE TITLE
Improvements in the efficiency of the GCD algorithm for javascript

### ISSUE THREAD

**Issue by aquine-kujaruk** [30-seconds/30-seconds-of-code#1094]
const gcd = (arr) => {
    const current = Math.min(...arr);
    const proc = (arr, current) => arr.filter(x => x % current !== 0).length === 0;
    const _gcd = (arr, current) => proc(arr, current) ? current : _gcd(arr, --current);
    return (current <= 1) ? 1 : proc(arr, current) ? current : _gcd(arr, Math.floor(current / 2));
}

**Comment by Chalarangelo** [comment]
Thanks for the idea. The current implementation is far easier to read and comprehend, even if less performant. I think we should stick to the existin solution as it also handles variadic arguments, too.
