### ISSUE TITLE
Add Data Structure and Algorithms 

### ISSUE THREAD

**Issue by Prottoy2938** [30-seconds/30-seconds-of-code#1097]
## Add Data Structure and Algorithms 

Data structures are needed when developing advanced applications. Often it's hard to find the code for a data structure. It would be better if 30 seconds of code can provide small snippets of useful data structures. If this feature is accepted, I can contribute a couple of data structures and some common algorithms.

**Comment by Chalarangelo** [comment]
Thanks for the feedback!
We have plans to add content like that in the future, however this might be a long ways down the road, as we decide on formats and guidelines. I will close the issue for now, as this might reside in a different repository and requires org-wide changes to be implemented.
