### ISSUE TITLE
AutoComplete Algorithm for Search Bar

### ISSUE THREAD

**Issue by Prottoy2938** [30-seconds/30-seconds-of-code#1098]
## AutoComplete Algorithm for https://www.30secondsofcode.org/ search bar

I can provide an algorithm, which would be able to give users related search suggestions based on the words that they typed on the search field. It would be pretty helpful for users, as they can see what kind of result they can get before they searched.

It would be similar to this: https://ingredient-d4129.firebaseapp.com/ 's search suggestions.

But I think my algorithm will run faster.

What'd you think

**Comment by Chalarangelo** [comment]
Thanks for the interest. However, due to certain implementation constraints, we have decided against this feature as it will significantly impact client-side performance across the website.
