### ISSUE TITLE
Looks like `p-side_a` and `p-side_c` is not defined in heronArea.md file

### ISSUE THREAD

**Issue by Prottoy2938** [30-seconds/30-seconds-of-code#1103]
## Undeclared file on heronArea.md file

 I think  `p-side_c` and `p-side_a` hasn't declared in the heronArea.md file. Same is true for all of its reference and test files.

**Comment by Chalarangelo** [comment]
We are deprecating the snippet archive, so `heronArea` will be removed alongside other snippets. Refer to #1125 for more information. Thank you.
