### ISSUE TITLE
Why md files are rendered as html in React applications

### ISSUE THREAD

**Issue by Prottoy2938** [30-seconds/30-seconds-of-code#1107]
## Looks like `.md` files are rendered as HTML in this application

I had browsed around this codebase and it looked like **.md** files are loaded as `HTML` in the browser. I have seen the same patterns for  [_Dan Abramov_'s](https://overreacted.io/) blog. I am still new to React, so I don't get this pattern.
 Why are these projects are using **.md** files? Why is there are no regular react component? Which part am I getting wrong? Can you point me in the right direction where I can learn more about this?

**Comment by Chalarangelo** [comment]
Hey, our infrastructure is a bit more complex than just this repository. Check [30-seconds-web](https://github.com/30-seconds/30-seconds-web) to see the engine powering the website, which is n turn based on [Gatsby](https://www.gatsbyjs.org/) which is responsible for the MD -> HTML conversion. Cheers!
