### ISSUE TITLE
https://www.30secondsofcode.org/js/s/reject/

### ISSUE THREAD

**Issue by 117028813** [30-seconds/30-seconds-of-code#1118]
## Description
https://www.30secondsofcode.org/js/s/reject/

Filters an array's values based on a predicate function, returning only values for which the predicate function returns true.

this description is wrong.

It should be:
Filters an array's values based on a predicate function, returning only values for which the predicate function returns false.

**Comment by Chalarangelo** [comment]
From what I see, you are correct. Please open a PR for it, if you have the time, I will review it shortly.

**Comment by rakeet** [comment]
. 
    On Friday, April 3, 2020, 04:49:27 AM EDT, Angelos Chalaris <notifications@github.com> wrote:  
 
 


From what I see, you are correct. Please open a PR for it, if you have the time, I will review it shortly.
