### ISSUE TITLE
https://www.30secondsofcode.org/js/s/is-sorted/

### ISSUE THREAD

**Issue by 117028813** [30-seconds/30-seconds-of-code#1123]
## Description

https://www.30secondsofcode.org/js/s/is-sorted/
This description is wrong:
Returns 1 if the array is sorted in ascending order, -1 if it is sorted in descending order or 0 if it is not sorted.
I think it should be:
Returns positive if the array is sorted in ascending order, negative if it is sorted in descending order or 0 if it is not sorted.
because I found:
`isSorted([0, 2, 4]); // 2`

**Comment by Chalarangelo** [comment]
The description is correct in describing the desired behavior. This is an issue in the implementation, instead. We could most likely evaluate why this is happening or just divide by the absolute value of `direction` to return the correct result. It's worth investigating and/or testing more in-depth before moving forward with a PR.

**Comment by 117028813** [comment]
```
const isSorted = arr => {
  let direction = -(arr[0] - arr[1]);
  for (let [i, val] of arr.entries()) {
    direction = !direction ? -(arr[i - 1] - arr[i]) : direction;
    if (i === arr.length - 1) return !direction ? 0 : direction / Math.abs(direction);
    else if ((val - arr[i + 1]) * direction > 0) return 0;
  }
};
```
Is this OK?

**Comment by Chalarangelo** [comment]
@117028813 seems about right to me, you can PR it!
