### ISSUE TITLE
【VSCode Plugin】Any idea about TypeScript support?

### ISSUE THREAD

**Issue by Lucien-X** [30-seconds/30-seconds-of-code#1137]
First of all, thanks for your contribution, this repo is really helpful for my daily develop🎉🎉🎉.

I was using [this](https://marketplace.visualstudio.com/items?itemName=30-seconds.30-seconds-of-code) vscode plugin for snippets support.

I follow the guideline, get all the necessary config done.

Unfortunately, this plugin only work with files with '.js' extention. ╮(╯▽╰)╭

**Is there any way, to configure the file type association ? Such as '.ts' and '.tsx', etc.** 🤔

**Comment by Chalarangelo** [comment]
Hey there. The VS Code plugin has been discontinued for a while now... Sorry for the inconvenience.
