### ISSUE TITLE
Created an app with JSONs available

### ISSUE THREAD

**Issue by adarsh0d** [30-seconds/30-seconds-of-code#1140]
I created an app with the data available in github repo,
You should check, it works completely offline, hence useful while preparing for last minute or during travelling.

I hope owners of data don't mind, else I will take it off.

https://play.google.com/store/apps/details?id=com.wolfpack.seccode

**Comment by Chalarangelo** [comment]
We would rather that people used the website itself as we can ensure that all of the information is up to date and also they can get the latest posts and snippets. :wink:
