### ISSUE TITLE
HTML tab

### ISSUE THREAD

**Issue by avijain10** [30-seconds/30-seconds-of-code#1148]
If you have two elements of frontend i.e., CSS and Javascript, then you should even add HTML.
If you agree to this, i can send the snippets for all the basics of HTML.
Please consider this and give my chance to step into it.
Thank you.

**Comment by Chalarangelo** [comment]
Hey there!

HTML has been discussed in the past and the reality is that there is very little not covered in already existing resources, therefore we will let others who already handle this topic well handle it instead of repeating the very same thing.
