### ISSUE TITLE
Uninstall extension, still get suggestions

### ISSUE THREAD

**Issue by petebdeblois** [30-seconds/30-seconds-of-code#1158]
Hi

I uninstall the extension a whil back, but when I type, I still get the suggestions 
I tried installing and uninstalling again, same issue. 
![Code_Y5nXJDH8IS](https://user-images.githubusercontent.com/20261852/84437461-052dfa00-ac03-11ea-8806-bdce5570a2d8.png)

Not sure if that's intended

**Comment by Chalarangelo** [comment]
Hello,

We are not affiliated with the extension and thus we cannot help with this issue. Please message the creator or file an issue in their repository to figure this out.

Thank you

**Comment by petebdeblois** [comment]
Maybe you should report it because every links on the extensions bring me here
https://marketplace.visualstudio.com/items?itemName=30-seconds.30-seconds-of-code
Issue ; https://github.com/30-seconds/30-seconds-of-code/issues

Publisher https://marketplace.visualstudio.com/publishers/30-seconds
https://30secondsofcode.org/ | 30secondsofcode@gmail.com

**Comment by petebdeblois** [comment]
You even made an announcement about it
https://github.com/30-seconds/30-seconds-of-code/issues/722#issuecomment-445311028

**Comment by Chalarangelo** [comment]
@petebdeblois Sorry, thought you meant the Chrome extension, my bad. The VSCode extension is discontinued for a while now, I think you manually have to remove any saved snippets from the extension or perform a clean install of VSCode.
