### ISSUE TITLE
some idea for clampNumber

### ISSUE THREAD

**Issue by shanyuhai123** [30-seconds/30-seconds-of-code#1161]
```js
const clampNumber = (num, a, b) => Math.max(Math.min(num, Math.max(a, b)), Math.min(a, b));

clampNumber(2, 3, 5); // 3
```
The description: 
Clamps num within the inclusive range specified by **the boundary values a and b**，so maybe change `a`、`b` to an array will be easier to understand.

```js
const clampNumber = (num, [a, b]) => Math.max(Math.min(num, Math.max(a, b)), Math.min(a, b));

clampNumber(2, [3, 5]); // 3
```

**Comment by Chalarangelo** [comment]
Thanks for the suggestion. As this is a breaking change and we want to keep the snippet an easy drop-in replacement for existing libraries, we'll leave it as is.
