### ISSUE TITLE
About the translated version

### ISSUE THREAD

**Issue by MangoTsing** [30-seconds/30-seconds-of-code#1163]
Hello administrator, I can provide a Chinese translation version so that all Chinese readers can easily read and can also contribute to the project.
Do you have the will to provide internationalization?

**Comment by Chalarangelo** [comment]
Thanks for the offer. We have discussed this in the past, however it's very hard to maintain, curate and ensure high quality and consistency for translations, so we have decided against this. If we ever decide to start adding translations, Chinese will probably be the first one we'll consider, so stay tuned!
