### ISSUE TITLE
js - unflattenObject: fails to correctly restore nested properties

### ISSUE THREAD

**Issue by tbasse** [30-seconds/30-seconds-of-code#1175]
The `unflattenObject` function works fine with the provided example

```
unflattenObject({ 'a.b.c': 1, d: 1 }); // { a: { b: { c: 1 } }, d: 1 }
```

But it won't work as expected on `{ 'a.b': 1, 'a.c': 2, d: 3 }`, returns an object with `a.b.` missing.
It also throws on nested values that are not numbers like `{ 'a.b': 'foo', d: 3 }`, results in `Unexpected token in JSON`.

See https://runkit.com/tbasse/5f2a9929c9b5c9001a4d3a6e for some tests

**Comment by Sparkadelic177** [comment]
I'll like to take a look at this issue.

**Comment by Chalarangelo** [comment]
@Sparkadelic177 Sure, go ahead! :ok_hand:

**Comment by pachbrasil** [comment]
Hum..

**Comment by Sparkadelic177** [comment]
@pachbrasil you can go for it if you want.

**Comment by shivichoudhary** [comment]
sure

**Comment by Taimoor0217** [comment]
@Sparkadelic177 can I please take this?

**Comment by geekylilgirl420** [comment]
Look I am totally lost on here. All I is my ex has access to all my accounts idk how but he is ruining my life.

**Comment by Taimoor0217** [comment]
@Chalarangelo I have opened a [pull request](https://github.com/30-seconds/30-seconds-of-code/pull/1220) for this.
Thankyou !
