### ISSUE TITLE
js - flattenObject: throws on null values and omits date objects

### ISSUE THREAD

**Issue by tbasse** [30-seconds/30-seconds-of-code#1176]
flattenObject omits date objects in the flattened result
`flattenObject({ a: { b: new Date() } }) // result: {}`

flattenObject throws when nested properties are `null`
`flattenObject({ a: { b: null }, d: 1 }) // TypeError: Cannot convert undefined or null to object`

See https://runkit.com/tbasse/5f2aaca10f979f00194eb236 for test cases

**Comment by Sparkadelic177** [comment]
If noone is not working on this, I would like to take a stab at it.

**Comment by Chalarangelo** [comment]
@Sparkadelic177 Sure, go ahead. Make sure to write `Resolves #1176` in the PR description and follow the guidelines. Happy coding! :smiley:
