### ISSUE TITLE
why deepClone do not use clone but obj

### ISSUE THREAD

**Issue by henrycjchen** [30-seconds/30-seconds-of-code#1183]
In the `snippets/deepClone`, there is a case to return `Array.from(obj)`, which make the clone object useless, is it correct to do so?

**Comment by rohansp** [comment]
I believe Array.isArray(obj) checks if obj is of type Array.  Array.from(obj) is the deep clone of the array .Correct me if I am wrong.

**Comment by Chalarangelo** [comment]
We're looking into this. I'll get back to you.

**Comment by henrycjchen** [comment]
> I believe Array.isArray(obj) checks if obj is of type Array. Array.from(obj) is the deep clone of the array .Correct me if I am wrong.

Array.from is actually the shallow copy of the array. You can check it from [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

**Comment by Chalarangelo** [comment]
Solved in de38320. The code was simplified and some notes were added for this.
