### ISSUE TITLE
Why do not add some use cases of the real-world in snippets description?

### ISSUE THREAD

**Issue by Jecyu** [30-seconds/30-seconds-of-code#1192]
when I review some snippets, I used to get stuck in what's the real-world problems does snippet solves as an example `sumPower` snippet.  This does not require the contributor to do more work, because he needs to consider the usage scenario of the code fragment before contributing. 

```
# Contribution Guidelines

## Ground rules

- Snippets should solve real-world problems, no matter how simple, and should be abstract enough to be applied to different scenarios.
```

**Comment by Chalarangelo** [comment]
Some of the snippets are more educational than used very often. This is especially true with math snippets, such as the one you mention. Providing real-world scenarios, while important, is not something we can document thoroughly sometimes.

**Comment by davoodgf** [comment]
#1192

**Comment by davoodgf** [comment]
#1192

**Comment by Jecyu** [comment]
> Some of the snippets are more educational than used very often. This is especially true with math snippets, such as the one you mention. Providing real-world scenarios, while important, is not something we can document thoroughly sometimes.

Thanks for your explanation. I got that.
