### ISSUE TITLE
Duplicating existing snippets with different coding paradimas

### ISSUE THREAD

**Issue by jikuja** [30-seconds/30-seconds-of-code#1299]
Is it suitable for this repository to duplicate existing snippets with different paradigms? 

E.g. rewrite code that uses a mutable accumulator with immutable functional code or rewriting callback styled/synchronous calls to promise-based implementations?

If that's ok is there any preferred naming policy for new versions?

**Comment by Chalarangelo** [comment]
We currently do not support multiple implementations per snippet. Maybe sometime in the future.
