### ISSUE TITLE
Digitize works incorrectly

### ISSUE THREAD

**Issue by Seasle** [30-seconds/30-seconds-of-code#1376]
Now `digitize` [snippet](https://www.30secondsofcode.org/js/s/digitize) works with only unsigned numbers:
```js
digitize(200); // [2, 0, 0]
digitize(-200); // [NaN, 2, 0, 0]
```
Can we update snippet to the next state?
```js
const digitize = n => [...`${Math.abs(n)}`].map((v, i) => i === 0 ? parseInt(v) * Math.sign(n) : parseInt(v));
```

```js
digitize(200); // [2, 0, 0]
digitize(-200); // [-2, 0, 0]
```

**Comment by ujalak1812** [comment]
@Seasle I have opened a PR for this issue, kindly review

**Comment by Chalarangelo** [comment]
Thanks for the heads up. The described behavior (returning the first digit as a negative) is unexpected, so we went ahead and fixed it to just ignore sign altogether.
