### ISSUE TITLE
Add Validators Snippets

### ISSUE THREAD

**Issue by arnabuchiha** [30-seconds/30-seconds-of-code#1402]
- [ ] Validate IPv4
- [ ] Validate Hexadecimal
- [ ] Validate EmailID
- [ ] Validate Phone Number

Can I work on these?

**Comment by Chalarangelo** [comment]
Not really, validation is outside the scope of this repo for the most part, as it requires a deeper understanding of a lot of concepts not explainable in 30s or less.
