### ISSUE TITLE
Add Harmonic Progression

### ISSUE THREAD

**Issue by arnabuchiha** [30-seconds/30-seconds-of-code#1403]
Can I implement this? It can be explained in 30 sec.

**Comment by Shaishav-Anand** [comment]
Hello @arnabuchiha  Can You Please Assigned It To Me I want to contribute to this it will be very great to do so.

**Comment by arnabuchiha** [comment]
@Shaishav-Anand Actually I made this issue for me to make a PR, also I cannot assign because I am not the maintainer.

**Comment by Chalarangelo** [comment]
I don't think we want a harmonic progression snippet at this time. Existing progression snippets are underperforming anyways, so we might be archiving them soon. Cheers.
