### ISSUE TITLE
Add Radio-Button Selected Snippet

### ISSUE THREAD

**Issue by crew-guy** [30-seconds/30-seconds-of-code#1428]
This snippet will help users derive and use which radio-button option is selected by the consumer while using the website.
It can be easily explained in 30s.
I used it in this project so thought it might become useful to others as well

[Expense Grapher Project](https://expense-grapher.netlify.app/)

May I please work on this ?

**Comment by Chalarangelo** [comment]
Not sure what you mean, but this sounds like a very specific case, so it's probably not generalized enough to publish on the website. Cheers.

**Comment by crew-guy** [comment]
No issues.
