### ISSUE TITLE
Typescript snippets

### ISSUE THREAD

**Issue by itamar244** [30-seconds/30-seconds-of-code#1431]
Maybe you should add typescript snippets?
It could be helpful for users, and it is a big part of the JS ecosystem these days.

Also, I saw you added snippets for python, so I think to add snippets to TS is perfectly fine.

If you agree with me, I would like to do it myself, both because I want to contribute and because I take part in the hacktoberfest 😄

**Comment by Chalarangelo** [comment]
Typescript is a project we might undertake in 2021 or so, but not right now. Closing, as we have neither the infrastructure nor the desire to work on this right now.
