### ISSUE TITLE
New snipper

### ISSUE THREAD

**Issue by coralhayoun** [30-seconds/30-seconds-of-code#1493]
Hi,
I've wnated to add a new snipper called countStringOccurrences, which counts the occurrences of a string in another string
for examle: 'tt' occurs twice at 'attbtt'
right now theres only countOccurrences of an item in an array
is it ok to add it?

**Comment by Chalarangelo** [comment]
Thanks for asking. `countOccurences` will work with strings if spread to arrays (`[...str]`), so it's pretty much the same snippet in reality, so we shouldn't add one more for strings.

**Comment by coralhayoun** [comment]
spread it to array would help you find character occurences but not another string occurences

**Comment by Trinityyi** [comment]
@coralhayoun Fair enough, `String.prototype.search()` or`String.prototype.indexOf()` in combination with `String.prototype.split()` will most likely do the trick then.
