### ISSUE TITLE
Scroll page by JS { with out giving href }

### ISSUE THREAD

**Issue by SushanthReddyManda** [30-seconds/30-seconds-of-code#1497]
I wanted to add JS function(s)  to scroll the page / go to a particular location  .
As giving this:-
```
<a href= "#some-id"> .....  </a>


<div  id="some-id"> ....... </div>
```
is a bit  time taking , and changes the base link as well .
To remove such thinks I came up with this idea .

Hope to hear from u soon .

**Comment by MoisesTR** [comment]
Hello man , can you assign me this? I worked in the utility

**Comment by christyram99** [comment]
HI @SushanthReddyManda , I would like to add a snippet for this issue.

**Comment by Chalarangelo** [comment]
This is a language feature - [`Window.scrollTo()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) - so it's not worth implementing a snippet that replicates this behavior.
