### ISSUE TITLE
Detec if a word it's an isogram

### ISSUE THREAD

**Issue by MoisesTR** [30-seconds/30-seconds-of-code#1500]
Hi all, I want to add this snippet which consist in: 
An isogram is a word that has no repeating letters, consecutive or non-consecutive

example :
 isIsogram("Dermatoglyphics") == true
 isIsogram("aba") == false
 isIsogram("moOse") == false // -- ignore letter case

**Comment by nishanth2143** [comment]
Hi @MoisesTR , I would like to take this up.

**Comment by m11dedhia** [comment]
Hey, could you assign this to be? I would like to complete it

**Comment by nishanth2143** [comment]
Hi @m11dedhia , I had already raised a PR for this change. 

https://github.com/30-seconds/30-seconds-of-code/pull/1507

**Comment by Chalarangelo** [comment]
As mentioned in #1507, this is not really worth adding, as its real-life applications are very limited.

**Comment by MoisesTR** [comment]
> As mentioned in #1507, this is not really worth adding, as its real-life applications are very limited.

It's ok, to be honest,  you're right.
