### ISSUE TITLE
Add number of days(excluding weekends) to a given date and return the new date.

### ISSUE THREAD

**Issue by nishanth2143** [30-seconds/30-seconds-of-code#1510]
Given the number of days and date, write a function to add the number of days (excluding weekends) to the date and return a new date.

Example:
If the number of days is 3 and date is Oct 09, 2020, then the function must return Oct 14, 2020

**Comment by nishanth2143** [comment]
@Chalarangelo , is this a valid scenario that would need working on?

**Comment by Chalarangelo** [comment]
I'd rather have a `countWeekDaysBetween` snippet that returns how many weekdays are between two days. So in your example, it would take `Oct 09, 2020` and `Oct 14, 2020` and return `3`. Could you implement that?

**Comment by nishanth2143** [comment]
Yes. On it.

**Comment by nishanth2143** [comment]
Change done in https://github.com/30-seconds/30-seconds-of-code/pull/1512

**Comment by Chalarangelo** [comment]
Thanks. While we are looking at the PR, you can submit another PR with the `addWeekDays` you mentioned. We took a quick look and it also seems reasonably valuable. :wink:

**Comment by nishanth2143** [comment]
Yeah sure!

**Comment by nishanth2143** [comment]
Done! https://github.com/30-seconds/30-seconds-of-code/pull/1517

**Comment by Chalarangelo** [comment]
Resolved in #1517
