### ISSUE TITLE
Random Greetings or Words based on the given set of words having similar meanings

### ISSUE THREAD

**Issue by Keyurkariya** [30-seconds/30-seconds-of-code#1514]
Define a set of words having similar meanings and they will be used randomly. 

For example, to greet someone we can use ['Hello', 'Hola', 'Namaste'], etc and it will be randomly used.

**Comment by Keyurkariya** [comment]
Can you assign this to me working on this PR

**Comment by Keyurkariya** [comment]
Here is a PR for the same : https://github.com/30-seconds/30-seconds-of-code/pull/1515

**Comment by Chalarangelo** [comment]
This is probably not very valuable to most readers.
