### ISSUE TITLE
Check if a given date is future to Today's date

### ISSUE THREAD

**Issue by rikkashini-personal** [30-seconds/30-seconds-of-code#1518]
If given a date in the format YYYY-MM-DD, check if the date is greater than or future to today's date.

Example: 
Date given: 2020-11-27,
Assumed Today's date: 2020-10-11,
then return **True**

**Comment by rikkashini-personal** [comment]
@Chalarangelo If it could be accepted as a valid issue, assign me to this.

**Comment by Trinityyi** [comment]
This would be the same as [isAfterDate](https://www.30secondsofcode.org/js/s/is-after-date).
