### ISSUE TITLE
Add snippet that checks if a point exists on a straight line between two other points

### ISSUE THREAD

**Issue by richard-oden** [30-seconds/30-seconds-of-code#1598]
If a straight line is drawn between point A and point B, return true if that line contains point C, otherwise return false.

I recently had to solve this in my own project. Would love to add if it's not a duplicate!

**Comment by Chalarangelo** [comment]
Thanks for the idea, but I think geometry snippets are mostly useful in graphics drawing, which is not an area we have much expertise in nor do we have any intent of adding snippets around those use cases right now.
