### ISSUE TITLE
Snippet for unique elements not considering non-primitive types

### ISSUE THREAD

**Issue by shabab477** [30-seconds/30-seconds-of-code#1632]
The code snippet for [uniqueElements](https://www.30secondsofcode.org/js/s/unique-elements) only works for non-primitive types. I found it extremely helpful to have a snippet where I would want unique objects because there are very little use cases where I would need a unique array of integers or unique strings. Rather, I would prefer a short snippet which takes into account non-primitive types. 

```js
const array = [
    {
        name: "Test 1",
        nested: {
            val: 1
        }
    },
    {
        name: "Test 1",
        nested: {
            val: 2
        }
    },
    {
        name: "Test 1",
        nested: {
            val: 1
        }
    },
];

// Returns 3 elements because Set doesn't understand non-primitive elements. 
// Would like it to return 2 elements 
uniqueElements(array);
```
I think instead of updating the existing snippet, there should be a separate snippet which handles the complexity.

**Comment by Chalarangelo** [comment]
[uniqueElementsBy](https://www.30secondsofcode.org/js/s/unique-elements-by) does exactly what you are describing.
