### ISSUE TITLE
Tower of Hanoi Solver

### ISSUE THREAD

**Issue by komputarist** [30-seconds/30-seconds-of-code#1636]
The Tower of Hanoi puzzle is a demo of how recursion works. 
It's a puzzle with 3 posts and multiple disks of different sizes.
The goal of the puzzle is to move all the disks from the first pole to the third pole according to the following rules :
1. Only one disk can be moved at a time.
2. You can only move the top disc in a stack.
3. No disk may be placed on top of a smaller disk.

**Comment by sanskritip** [comment]
I would like to work on this issue!

**Comment by Chalarangelo** [comment]
No, thanks. This is not at all useful to the average reader.
