### ISSUE TITLE
isObjectEmpty checking snippet

### ISSUE THREAD

**Issue by christyram99** [30-seconds/30-seconds-of-code#1652]
isObjectEmpty will check the object empty or not.

**Example:**
```js
isObjectEmpty({}) // true
isObjectEmpty({ a: 1 }) // false
```

**Comment by Trinityyi** [comment]
[isEmpty](https://www.30secondsofcode.org/js/s/is-empty) does exactly what you are describing.

**Comment by christyram99** [comment]
Got it @Trinityyi .
