### ISSUE TITLE
parseCookie: Support for stripping double quotes escapes.

### ISSUE THREAD

**Issue by dostiharise** [30-seconds/30-seconds-of-code#1709]
The [parseCookie](https://github.com/30-seconds/30-seconds-of-code/blob/master/snippets/parseCookie.md) snippet doesn't support cookie parameter values that are escaped using a double quote `"`

Example: 

The header `Set-Cookie: who-are-you="i-am-a-cookie"; Path=/` results in Cookie Name `who-are-you` and Cookie Value as `"i-am-a-cookie"`.

When you read the cookie value, you may want to strip away the double-quote `"` from `"i-am-a-cookie"` and return `i-am-a-cookie`. 

Refer here:

- [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1)
- [MDN Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)

**Comment by CreaTorAleXander** [comment]
I would like to do this.

**Comment by dostiharise** [comment]
Great, you could raise a pull request. I can help review & validate your PR.

cc: @Chalarangelo, @fejes713

**Comment by CreaTorAleXander** [comment]
So shall I just use the same example but with double quotes? Or ist there something else I have to think about?

**Comment by dostiharise** [comment]
I think editing the same snippet with necessary comments will help. 

Once you have a PR, the maintainers will hopefully review and give you comments to improve.

Let's be ready to do multiple iterations. 🙂

I would add the necessary code that would strip away double quotes on left and right from the before `decodeComponent` is called and not after.

**Comment by dostiharise** [comment]
Now that I think about it I am not sure if `decodeComponent` is the right solution.

Because the decode must actually take place inside the app logic, and the cookie value must be treated as is. 

🤔

**Comment by CreaTorAleXander** [comment]
Are leading empty spaces are possible in Cookie Values?
``who-are-you=     "i-am-a-cookie"``

**Comment by dostiharise** [comment]
No. Spaces are not allowed. 

You can refer here: [HTTP Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies).

**Comment by CreaTorAleXander** [comment]
Ok well, ty

**Comment by Chalarangelo** [comment]
This issue is invalid. Cookie values should be parsed as-is and it's upon the developer to handle anything after that. The snippet does what it says on the box - parses the cookie. Edge-cases and additional handling is out of scope.
