### ISSUE TITLE
isNode null checks should account for undefined

### ISSUE THREAD

**Issue by jasco** [30-seconds/30-seconds-of-code#1731]
The `isNode` check should probably use truthy checks rather than `null` checks.  `process.versions` and `process.versions.node` are more likely to be undefined than null.

```js
const isNode = () =>
  typeof process !== 'undefined' &&
  !!process.versions &&
  !!process.versions.node;
```

**Comment by MADTechMarket** [comment]
true, rather than null checks should be used

**Comment by l3aoNgoc** [comment]
Hhh
