### ISSUE TITLE
Do we have any plans to translate into other languages?

### ISSUE THREAD

**Issue by baooab** [30-seconds/30-seconds-of-code#1766]
Hello, I would like to ask, do we have any plans to translate into other languages? I want to translate these codes into Chinese~

**Comment by Chalarangelo** [comment]
As we have stated many times in the past, translations are not going to be part of our roadmap, probably ever. It's very hard to find contributors that will be dedicated to follow along in the long term and it will only slow us down and create outdated content. As far as we're concerned, Google Translate is a great way to view the website in another language. Cheers!

**Comment by divineBayuo** [comment]
Maybe a little competition for them could shake it things up.
