### ISSUE TITLE
Wrong result for some inputs

### ISSUE THREAD

**Issue by tomer-gavish** [30-seconds/30-seconds-of-code#1817]
In case a doubled digit equals to 0, the sum is miscalculated and the result is wrong.
For example, the following valid number returns `false` instead of `true`:
```javascript
luhnCheck('4024007174941954');
```
Or a shorter version:
```javascript
luhnCheck('406'); // false, but should be true
```

A possible solution would be to replace the reducer function with this:
```javascript
(acc, val, i) => (i % 2 !== 0 ? acc + val : acc + ((val *= 2) > 9 ? val - 9 : val))
```

The fix has been tested against all [Paypal's credit card numbers for testing](https://developer.paypal.com/docs/payflow/payflow-pro/payflow-pro-testing/#credit-card-numbers-for-testing).

**Comment by gitTheArindam** [comment]
> In case a doubled digit equals to 0, the sum is miscalculated and the result is wrong.
> For example, the following valid number returns `false` instead of `true`:
> 
> ```js
> luhnCheck('4024007174941954');
> ```
> 
> Or a shorter version:
> 
> ```js
> luhnCheck('406'); // false, but should be true
> ```
> 
> A possible solution would be to replace the reducer function with this:
> 
> ```js
> (acc, val, i) => (i % 2 !== 0 ? acc + val : acc + ((val *= 2) > 9 ? val - 9 : val))
> ```
> 
> The fix has been tested against all [Paypal's credit card numbers for testing](https://developer.paypal.com/docs/payflow/payflow-pro/payflow-pro-testing/#credit-card-numbers-for-testing).

In this fix also "6011329933655299" is returning true, where it should be false.
