### ISSUE TITLE
Better solution for "Returns the difference between two arrays."

### ISSUE THREAD

**Issue by decpk** [30-seconds/30-seconds-of-code#1839]
Why use `Set` here when we can use [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

The solution that is provided is

`const difference = (a, b) => {
  const s = new Set(b);
  return a.filter(x => !s.has(x));
};
difference([1, 2, 3], [1, 2, 4]); // [3]`

But I think there is a better solution available though the time complexity will be exactly the same and space complexity will be constant instead of O(n)

`const difference = (a, b) =>  a.filter(x => !b.includes(x));
difference([1, 2, 3], [1, 2, 4]); // [3])`

**Comment by Trinityyi** [comment]
Using `Array.prototype.includes()` is the naive approach as it doesn't account for duplicates and has a far greater complexity in most cases. Using a `Set` ensures that the lookup is as fast as possible and past benchmarks have hinted that most JS engines handle operations on `Set` objects faster in edge-cases of this snippet. We'll stick to this implementation for the time being.
