### ISSUE TITLE
scrollToTop issue

### ISSUE THREAD

**Issue by baixiaoyu2997** [30-seconds/30-seconds-of-code#1852]
when i run scrollToTop ,  still scroll up when i scroll down manually

**Comment by Anshu-jindal** [comment]
It's working fine on my PC. Could you give more details as to what problem are you facing?

**Comment by KushalUpreti** [comment]
Since the issue is still open can anyone elaborate on this issue?

**Comment by satyams00** [comment]
It's working fine.

**Comment by baixiaoyu2997** [comment]
sorry for delay, i made  a demo:https://codesandbox.io/s/reverent-rhodes-c9nuz?file=/src/styles.css
just click `Top`button ,when the scroll bar has not reached the top, scroll down 。

**Comment by anshkhandelwal12** [comment]
Can anyone tell me that this issue is open is yet or not

**Comment by Chalarangelo** [comment]
This is the expected behavior and implemented pretty much universally like that across the web.
