### ISSUE TITLE
related to #1862

### ISSUE THREAD

**Issue by code978** [30-seconds/30-seconds-of-code#1864]
Thanks, Angelos Chalaris for undertaking my previous pull request. 
I tried to implement two things : 
- snippet I added in the pull request related to node js different inbuild modules. 
- code is more readable but I can understand didn't make any meaning. 
- But what about the snippet which I trying to add in pull request 1861. 
- Can you please accept the `node.js module` snippet because I spend so much time to the written the definition of this node js module. 
- Also I want to know how I can contribute this repo so that this helps more people.

**Comment by rigan0707** [comment]
Hi

**Comment by Bhaskar2000pytom** [comment]
Wow, I can help you
