### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [30-seconds/30-seconds-of-code#1946]
Hello, I found 2 broken links:

- [x] https://30secondsofcode.org/snippes/p/1 (file: README.md, status code: 404)
- [x] js/s/node-list-to-array (file: snippets/js/s/iterable-to-array.md, status code: 404, last link in: https://www.30secondsofcode.org/js/s/iterable-to-array/)

**Comment by Chalarangelo** [comment]
Thanks for the report, will fix asap!

**Comment by Chalarangelo** [comment]
I made the relevant changes, next build should update the internal link in the relevant snippet. Thanks again for the report.

**Comment by ndsvw** [comment]
No problem. 👍

**Comment by Ryanford02** [comment]
#1941
