### ISSUE TITLE
passive-scroll-listener-performance has obsolete/incorrect advice

### ISSUE THREAD

**Issue by rebelmusic** [30-seconds/30-seconds-of-code#1964]
Hello there, this is the page in question: https://www.30secondsofcode.org/js/s/passive-scroll-listener-performance/

According to the specifications, adding passive: true to scroll is not necessary:

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners

**Comment by Grenish** [comment]
@rebelmusic Hi there! Thank you for raising this issue. The use of `{ passive: true }` in a scroll event listener is related to optimizing browser performance. It indicates that the listener won't prevent default scrolling behavior.
If your code inside the listener doesn't include actions that prevent default behavior, like  `event.preventDefault()`, then `using { passive: true }` might be unnecessary. Browsers may interpret it differently, and testing in your specific context will help decide if it's beneficial.

## Related Issue
Fixes #1964

**Comment by Chalarangelo** [comment]
@Grenish is actually correct in his answer. Thanks everyone for your patience. I'm closing this as wontfix, due to the advice being correct.
