### ISSUE TITLE
style: Centering the footer section ⏡

### ISSUE THREAD

**Issue by bharathkalyans** [30-seconds/30-seconds-of-code#1974]
* As you can see in the below snapshot, the footer is aligned to the left part of the page.
* Aligning it to the center would make the page cleaner.
<img width="1439" alt="Screenshot 2023-08-07 at 9 46 17 AM" src="https://github.com/30-seconds/30-seconds-of-code/assets/49526472/21acbaa0-22a9-4fc7-abb1-e81a850ac03e">

**Comment by rahuljha4171** [comment]
Hi, Can you assign me this issue?
