### ISSUE TITLE
cookie parsing containing a `=` in value

### ISSUE THREAD

**Issue by cmgchess** [30-seconds/30-seconds-of-code#1992]
https://github.com/30-seconds/30-seconds-of-code/blob/master/snippets/js/s/parse-cookie.md

if a cookie value contains an `=` would this break

**Comment by cmgchess** [comment]
```javascript
const parseCookie = (str) =>
  str
    .split(';')
    .map((v) => {
      const equalSignIndex = v.indexOf('=');
      const name = v.substr(0, equalSignIndex).trim();
      const value = v.substr(equalSignIndex + 1).trim();
      return [name, value];
    })
    .reduce((acc, [name, value]) => {
      acc[decodeURIComponent(name)] = decodeURIComponent(value);
      return acc;
    }, {});
```

**Comment by cmgchess** [comment]
> const parseCookie = str => str .split(/;\s(?![^=]+=[^=]+)/) // Split only on semicolons followed by a space, not preceded by an equal sign .map(v => v.split('=')) .reduce((acc, v) => { acc[decodeURIComponent(v[0].trim())] = decodeURIComponent(v[1].trim()); return acc; }, {});

```
console.log(parseCookie('foo=bar; equation=E%3Dmc%5E2'))
//{ foo: "bar; equation" }
```

**Comment by nitikrimjial** [comment]
To avoid this problem, you should encode any = characters in cookie values using the encodeURIComponent() function.
`document.cookie = `foo=${encodeURIComponent('foo=bar')}`;`

**Comment by Chalarangelo** [comment]
Thanks for opening an issue about this. As shown in the example below the code, if properly encoded, `=` is not going to be a problem. [`parseCookie`](https://www.30secondsofcode.org/js/s/parse-cookie/) is meant to be used in combination with [`serializeCookie`](https://www.30secondsofcode.org/js/s/serialize-cookie/), explaining the "correct" way to store and retrieve cookie values.
