### ISSUE TITLE
[ BUG ] Missing space in footer section

### ISSUE THREAD

**Issue by RuthwikReddy09** [30-seconds/30-seconds-of-code#1994]
There is a space missing after "2017-2023" in the footer section. 

Screenshot : 
<img width="329" alt="Screenshot 2023-08-27 095913" src="https://github.com/30-seconds/30-seconds-of-code/assets/126862059/15415360-02d0-4584-b5b7-401d9fa46f90">

Steps to Reproduce : 
1. Open https://www.30secondsofcode.org/
2. Go to the footer section

**Comment by raoankitx** [comment]
Just Simply Add `&nbsp` paragraph element 
<img width="487" alt="Screenshot 2023-08-27 at 2 20 23 PM" src="https://github.com/30-seconds/30-seconds-of-code/assets/79178437/cb4987da-b0a5-49f1-962d-ad7ce9b52f0b">

**Comment by nexuspy** [comment]
Is it still open can you assign it to me ?

**Comment by manoj515876** [comment]
Can I do it .

**Comment by manoj515876** [comment]
Can you assign me?

**Comment by Tanush-J** [comment]
The CONTRIBUTE.md mentions we are allowed to contribute only to snippets and collections, and this is an issue in the footer section. So, we can't fix this... I think.

**Comment by Harsha-10** [comment]
Yeah

**Comment by Bishwajitpvt** [comment]
If this issue is still active, I can work on it

**Comment by prateek-719** [comment]
Please assign to me

**Comment by Urvi-Pandit** [comment]
&nbsp should be added in the footer element. It stands for non breaking space, which is a space that will not break into a new line. There are a couple of more fixes too:
1. CSS white-space Property: The white-space property allows you to specify how white space should be handled within an element. Ex: white-space: nowrap;
2. CSS Margins, Padding and letter-spacing Property: These features can be adjusted in CSS to get the required effects.

**Comment by faizalmsdev** [comment]
can you assign it to me if its still on open?

**Comment by nitikrimjial** [comment]
To insert a non-breaking space in a paragraph element, use the HTML entity &nbsp; .
