### ISSUE TITLE
Typo in the event-loop-explained.md snippet

### ISSUE THREAD

**Issue by kevinweejh** [30-seconds/30-seconds-of-code#2015]
Hello maintainers/contributors,

While going through the [Event Loop Explained](https://www.30secondsofcode.org/js/s/event-loop-explained/) page, I found a typo in the markdown content, specifically in the file located at content/snippets/js/s/event-loop-explained.md.

On line 96, the content reads:

`10. The Event Loop checks the Microtask Queue. As it’s not empty, it executes the first Microtask, which is the callback of Promise.prototype.then() that was queued in step 10.`

However, the callback for Promise.prototype.then() was queued in step 9, not step 10. For reference, step 9 states:

`9. Promise.prototype.then() is pushed to the Call Stack and executed. This creates a new entry for its callback function in the Microtask Queue.`

To fix this, the end of the sentence in step 10 should be corrected to "... that was queued in step 9."

I have searched through the open issues and found no duplicates of this issue. As such, may I work on this issue?

Thank you for maintaining this resource! Let me know if I should go ahead and create a PR to fix this typo.

**Comment by Chalarangelo** [comment]
Yes, feel free to open a PR for this and mention this issue. Thanks for the report.

**Comment by kevinweejh** [comment]
Thank you for assigning this to me @Chalarangelo 
I'll work on it and submit a PR shortly.
