### ISSUE TITLE
Terminology issue in blog

### ISSUE THREAD

**Issue by kamtoeddy** [30-seconds/30-seconds-of-code#2021]
Hi maintainers,

Going through the interview prep. resource on [variable hoisting](https://github.com/30-seconds/30-seconds-of-code/blob/master/content/snippets/js/s/variable-hoisting.md), I noticed that the first sentence of the first paragraph had an issue.

It goes "Before your JavaScript code is executed, it is first parsed and `compiled`". My problem here is *`compiled`*. JavaScript is an interpreted language.

Thanks

**Comment by Chalarangelo** [comment]
It might be a little confusing, but technically it's true as JavaScript engines use a **JIT (just in time) compiler** to execute the code. If you can suggest a less confusing explanation that won't complicate things for beginners, feel free to comment down below as it might be worthwhile.

**Comment by kamtoeddy** [comment]
Awesome

Your response is spot-on. We could say something like "Before your JavaScript code is executed, it is first parsed and compiled([just-in-time compilation]())". 

I think putting JIT there and a link to a resource that will provide more clarity on what JIT is all about. This could even be a small(yet detailed enough) paragraph at the end of the article if you like

**Comment by mohanadft** [comment]
> Hoisting is a JavaScript mechanism where variables and function declarations are moved to the top of their scope before code execution by the parser which reads the source code into an intermediate representation before the actual execution starts by the JavaScript interpreter.

Before any execution, and before interpreting the code, hoisting is done during the parsing phase.

**Comment by mohanadft** [comment]
Moreover, for the one who want to make a pull request, you might add that hoisting is done only in non-strict mode, and can be avoided by using "use strict" at the beginning of the file.

**Comment by brolen89** [comment]
R5
