### ISSUE TITLE
[FEATURE] Experimental/Unstable/Low-support Browser API snippets

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-code#673]
I was thinking about adding a few snippets for Browser APIs that are not well-supported or are a bit experimental. Ideas include but are not limited to:

- Ambient Light
- Offline state
- Vibration (maybe)
- Device orientation

The question here is if we should make a new category or just tag them properly and add an emoji to all of them. I am leaning towards tags and emoji.

*If you are wondering why provide devs with experimental or unstable code - because the web is evovling and getting your hands on the new tech early on is one of the best learning experiences you can have!*

**Comment by skatcat31** [comment]
We should tag them and label them as experimental(if this is an emoji them that's fine) like you suggested. It makes easy low hanging branches of (removing experimental flags)/(keeping current) when they get updated, released, or finalized

**Comment by Chalarangelo** [comment]
So we can tag but without making a new category. Tags will help us find them when we need to, right? Experimental emoji should be a test tube like ⚗️(was looking for something better, but I couldn't find one).

**Comment by skatcat31** [comment]
⚡️, 📦, ⚙️, 🔨, ❌ are my votes for possible besides the beaker. I like the `:package:` myself

**Comment by skatcat31** [comment]
We should visit this more, but with how quickly the JS landscape changes I'm not certain how applicable this is anymore, just 5 months later

**Comment by Chalarangelo** [comment]
There will always be some API that is expreimental or some code that isn't well-supported yet. Maybe keep an issue open to list anything interesting that comes to our attention that we have no snippets for? That could come in handy in the long run!

**Comment by Chalarangelo** [comment]
This issue is essentially dead, so I'm gonna close it. If anyone touches experimental tech, note the following:
- Tag as `experimental` (not as primary tag). 
- Inform us of the experimental nature of the tech, link to docs, make it pretty clear we should do something about this snippet that clearly is not ready for production, so we can properly present it to users.
