### ISSUE TITLE
[FEATURE] Integration for VS Code

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-code#722]
As the codebase has grown a lot, I think it's time for a major addition to our repository - **a file to add our snippets to VS code**. This should be built daily and include everything in the normal list (no archive). 

### Why
I've found myself using some of our snippets a lot. And I am thinking about transitioning to VS Code, so this sounds like one of the things that I would definitely use in my daily life. It's also probably quite easy to write a script that produces them and state that we officially support VS Code as we can integrate with it (maybe even make an extension for it that we update regularly). 

Opinions are appreciated, but I think there's no harm in doing this and it will probably help a few people be more productive.

*I am aware of the fact that some side projects were made back in the day to support this, but I'd rather support this from inside the repo, as a core feature, so we can do more with it and maintain it properly.*

**Comment by skatcat31** [comment]
If it's a package with JSDoc documentation(which IIRC can support markdown), VS Code will pull it in. It may be worth it to put the documentation in there so that VS Code can show it when it crawls the package

**Comment by Chalarangelo** [comment]
@skatcat31 The idea I was trying to sell here was to allow people to use the snippets without the `npm` package - essentially copy paste their code for them without including the 30 seconds package. I am not really sure what you mean, please elaborate a bit.

**Comment by 10t4cL** [comment]
Is this still a planned feature? It sounds like something I could use on a daily basis!

**Comment by Chalarangelo** [comment]
@skatcat31 Apart from that, there is incentive to use snippets instead of a package to avoid adding a ton of dependencies that might not be maintained in the long run. And based on the fact that 30code offers a wide variety of snippets that correlate to single-function packages, it might offer a choice to developers who do not want to include them.

... We can always do both. Implementing these features is nearly trivial, we just don't have that much time lately.

**Comment by RubenMateus** [comment]
i agree, this would make sense to be an extension, i can gladly help!

**Comment by fejes713** [comment]
Can't wait for this one @Chalarangelo 😃 Please keep us posted on update from Azure team

**Comment by Chalarangelo** [comment]
Yup, I will!

**Comment by Chalarangelo** [comment]
The extension is finally live on VSCode Marketplace! Check it out [here](https://marketplace.visualstudio.com/items?itemName=30-seconds.30-seconds-of-code) and remember to download and rate if you can, we need the popularity boost in order to get more people involved in the development of 30-seconds.
