### ISSUE TITLE
[META] Update Issue and PR templates

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-code#730]
After the initial phase of 30s where we had tons of people submitting PRs and opening issues, I think that the community has more of a reference point for interacting with the code and repo in general. The templates we made back then for issues and PRs are starting to feel cumbersome and a bit unnecessary. I think we should revamp them. What do you guys think? How can we simplify the templates to improve user experience?

**Comment by skatcat31** [comment]
Are we allowed to have multiple templates like GL can?

**Comment by Chalarangelo** [comment]
@skatcat31 not sure, never tried it, I'll look it up and see if and how this is possible.

**Comment by Chalarangelo** [comment]
@skatcat31 Apparently we can have multiple Issue templates, check my last PR for a suggestion.

**Comment by Chalarangelo** [comment]
Issues have been updated, PRs as well. Multiple issue templates help users navigate to a specific issue type and provide the important info without having to shift throught a lot of stuff, which I am particularly fond of.
