### ISSUE TITLE
[FEATURE] 30 seconds of code - React snippets

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-of-code#739]
After some internal discussion and the idea floating around for a bit, I think we should go ahead and brainstorm a bit about adding **React snippets** in the repository, as a separate page, folder etc.

The idea is to provide a basic cheatsheet for React, much like the base repository, except this will be a sub-project (as it is part of the JS ecosystem and we are probably not going to have snippets in the hundreds in this category). I've started compiling a list of popular StackOverflow questions and answers that might prove useful. Add your suggestions below and let's get a decently-sized list ready for October, when [Hacktoberfest](https://hacktoberfest.digitalocean.com/) starts and we can expect a decent flow of PRs.

### My completely incomplete list of ideas

- `Array.map()` to create a row in a table (or similar) / [SO question](https://stackoverflow.com/a/22877110/1650200)
- Set focus on input after render using `componentDidMount` / [SO Question](https://stackoverflow.com/a/28890330/1650200)
- Force rerender / [SO Question](https://stackoverflow.com/a/30626072/1650200)
- Pass data on `onClick` event with arrow functions / [SO Question](https://stackoverflow.com/a/29810951/1650200)
- Keying groups of items? / [SO Question](https://stackoverflow.com/q/28329382/1650200)
- Custom version of `shouldComponentUpdate` for component, if we have a good example for that / [SO Question](https://stackoverflow.com/a/24719289/1650200)
- Debounce in React / [SO Question](https://stackoverflow.com/a/28046731/1650200)
- Show/Hide Component / [SO Question](https://stackoverflow.com/a/24534492/1650200)
- Conditional attributes on components / [SO Question](https://stackoverflow.com/a/31164090/1650200)
- Using booleans for `selected <select>` / [SO Question](https://stackoverflow.com/a/21736116/1650200)
- Update array in state / [SO Question](https://stackoverflow.com/a/26254086/1650200)
- Props inside quotes with template literals / [SO Question](https://stackoverflow.com/a/30061326/1650200)
- Pass props to parent / [SO Question](https://stackoverflow.com/a/31756470/1650200)
- How to use `mapDispatchToProps` / [SO Question](https://stackoverflow.com/a/40068198/1650200)
- Properly altering state, using `this.setState`, too many people ask this / [SO Question](https://stackoverflow.com/a/30783011/1650200)
- Call child method from parent / [SO Question](https://stackoverflow.com/a/37950970/1650200)
- Detect click outside component (advanced) / [SO Question](https://stackoverflow.com/a/42234988/1650200)
- Multiple CSS classes for component / [SO Question](https://stackoverflow.com/a/34521945/1650200)
- Conditionally apply classes / [SO Question](https://stackoverflow.com/a/30533260/1650200)
- `setState` with dynamic key name / [SO Question](https://stackoverflow.com/a/29281499/1650200)
- Validate `propTypes` of nested object / [SO Question](https://stackoverflow.com/a/26924696/1650200)
- `setState` with nested objects / [SO Question](https://stackoverflow.com/a/18934259/1650200)
- Component inside component / [SO Question](https://stackoverflow.com/a/31757397/1650200)
- `update` immutability helper / [SO Question](https://stackoverflow.com/a/29537485/1650200)
- Multiple inline styles / [SO Question](https://stackoverflow.com/a/37299564/1650200)
- Remove element from array in state, a bit too basic maybe / [SO Question](https://stackoverflow.com/a/31838774/1650200)
- Add `<script>` via React / [SO Question](https://stackoverflow.com/a/34425083/1650200)
- Form data in React / [SO Question](https://stackoverflow.com/a/23428536/1650200)
- Allow one of multiple types in `propTypes` / [SO Question](https://stackoverflow.com/a/41808543/1650200)
- Add `:hover` styles / [SO Question](https://stackoverflow.com/a/28369384/1650200)
- Dynamic component name, not sure if this works and how / [SO Question](https://stackoverflow.com/a/29876284/1650200)

**Comment by skatcat31** [comment]
You should add Modals as they're extremely helpful to have a dynamic modal that closes on click away from the child

**Comment by ShawnToubeau** [comment]
Hello! Hope you don't mind me adding to this list :) 

- Spread notation / [SO](https://stackoverflow.com/questions/31048953/what-do-these-three-dots-in-react-do)
- Controlled vs uncontrolled input / [SO](https://stackoverflow.com/questions/37427508/react-changing-an-uncontrolled-input)

Noticed a handful of posts asking about React-Router, would that be something you would want to focus on as well?

**Comment by skatcat31** [comment]
Spread notation is something that's well documented and used in few places, but has definate hlepful places(styles are a big one), and controlled versus uncontrolled input is a huge contention point in React, so it'd be smart to touch base on it. It's something I don't really think about myself since the coding guidelines I implemented enforced controlled at my last job(considered a best practice to guard against injection and cross site)

**Comment by skatcat31** [comment]
As for organization I think a separate folder or project would be best here. Also to note about Modal is that there are full screen modals based on events, and middle man modals based on parent container. Both would be helpful since I've found more pages struggling with modals.

**Comment by Chalarangelo** [comment]
**Update**: Having tested subdomain support on Github pages, I have to report we *need* to move React snippets into their own repo, as it's the only feasible way to host them under `react.30secondsofcode.org`. Probably a good idea, too, as it will help with separation of concerns. Only issue there is that star count will not be shared, but that's probably alright.

In light of this, I think we should close the issue and go on ahead to create a new repo over the weekend to get started. What do you guys say?

**Comment by fejes713** [comment]
Better idea to me honestly. 

30code should stay 30code and provide snippets for vanilla JS only. 

30react is a great idea, for the very start, I don't think we need a lot of snippets. Let's keep the focus on quality. If you're up to, we can develop under private repo and then make it public (for the big reveal 💯)

**Comment by Chalarangelo** [comment]
@fejes713 We can't do private repo on org without paying, plus I wanted this to be a good starting point for Hacktoberfest participation, I will make a new repo and see if I can migrate the issue over to it.

**Comment by fejes713** [comment]
Idea was to make it under user private repo, but as you said Hacktoberfest is here very soon, so we should give people opportunity to make something great!

**Comment by Chalarangelo** [comment]
This issue was moved to 30-seconds/30-seconds-of-react#1
