### ISSUE TITLE
[FEATURE] Random snippet of the day

### ISSUE THREAD

**Issue by dimabory** [30-seconds/30-seconds-of-code#747]
I'd like to return random snippets feature to the site. 

Why it was deleted?

**Comment by Chalarangelo** [comment]
Maybe we could dedicate a page to this, but without the annoying carousel and all the issues we previously had with that.

**Comment by flxwu** [comment]
We could also launch a newsletter?

**Comment by dimabory** [comment]
I also thought about the separate page for this. But anyway a newsletter is a good idea too.

**Comment by flxwu** [comment]
We could launch a separate newsletter on PH to boost the 30secs projects, kind of what I thought of doing on twitter but latter currently won't work till they approve my developer account @Charlangelo

**Comment by skatcat31** [comment]
I'm a little confused on how we'd get enough material unless we wanted to start targeting or writing articles or small thoughts(which get tricky and would likely need to be stockpiled before first publication for editing and accuracy). I'm all for it TBH, but it is a bit of logistics to be able to say we're doing things right

**Comment by meetzaveri** [comment]
Or a twitter bot ?

**Comment by Chalarangelo** [comment]
@meetzaveri I think @flxwu is up to something on Twitter... We'll probably find out soon enough.

**Comment by meetzaveri** [comment]
Okay, good to know.

**Comment by dimabory** [comment]
Btw, I can help with Telegram bot.

**Comment by flxwu** [comment]
Yes, I am working on the Twitter Bot.

**Comment by flxwu** [comment]
Closing this for now, as the @30-seconds/core team decided not to launch a separate newsletter. We'll instead launch a Twitter Bot somewhen soon.

**Comment by fejes713** [comment]
We're present on Instagram and Facebook as well. Sharing useful snippets daily!
