### ISSUE TITLE
Snippets in UltiSnips format

### ISSUE THREAD

**Issue by sQVe** [30-seconds/30-seconds-of-code#759]
I found this awesome project today and instantly wanted to _"install"_ it to use as snippets in **Vim**. I couldn't find it anywhere so I wrote a parser and created a repository here: [30-seconds-of-code-ultisnips](https://github.com/sQVe/30-seconds-of-code-ultisnips).

If it should live somewhere else, **please** do tell me. I initially planned to make a PR to the other *texteditor* repository, but I wanted to include a parser to try to keep the snippets as up-to-date as possible.

**Comment by Chalarangelo** [comment]
I like this idea. However, maintainance is usually an issue with companion repositories - hopefully you can set it up in such a way that the repository auto-updates.

I think it can reside where it is right now, if we somehow decide to integrate the format into our own release flow, I will inform you right away!

**Comment by sQVe** [comment]
@Chalarangelo Yeah, I get that. I have no problem with it residing at its' current home, I just wanted to let you guys know about it and let you decide. I'd love to somehow setup some kind of CI build that would update the repository automatically but I currently do not have time for that.

I'll try to keep it as up-to-date as possible and might also expand into other snippet formats, if I see a need. Another little side note is that I'm working on a CLI app for the 30 seconds snippets too (I'm a Arch Linux terminal junkie).

**Comment by Chalarangelo** [comment]
@sQVe I'd love to see that in action, send us a message (or comment on this issue) when it's done!

**Comment by sQVe** [comment]
@Chalarangelo Will do. I got pretty far today. Searching (generating index) and displaying works nicely. Just have to make it more customizable with options.

This is currently what it looks like:
![screenfetch-2018-10-01_22-30-02](https://user-images.githubusercontent.com/2284724/46314191-2931df00-c5ca-11e8-8144-9c095e9aae08.png)

**Comment by sQVe** [comment]
@Chalarangelo Project is moving forward, but slowly. One issue I'm having is that I rely on adding this repository as a submodule to get the `snippet_data`. I would prefer to import this from the `npm` module. Would it be possible to remove the exclusion of `snippet_data` from `.npmignore`?

**Comment by sQVe** [comment]
@Chalarangelo First release is now out. I've made a little notice here: https://github.com/30-seconds/30-seconds-of-code/issues/837. You can find the repo at: [30s](https://github.com/sQVe/30s)

**Comment by sQVe** [comment]
@Chalarangelo I've now added `CI` to the *UltiSnips* repo which runs a `cron` to update daily. This should keep the repositories in sync good enough.

I will probably expand the *UltiSnips* repository to include parsers for `VSCode`, `Atom` and `Sublime`. Time is the only issue.
