### ISSUE TITLE
indexOfAll.test.js should change comments for test of searching for val in array that doesn't contain val

### ISSUE THREAD

**Issue by itchylol742** [30-seconds/30-seconds-of-code#766]
## Bug description 

Currently the test which searches for 4 in array [1,2,3] has the comment 'Returns all indices of val in an array', but it should be changed to describe that it tests the function when val is not found. I would like to work on this issue by changing it to 'When val is not found, return an empty array'
## Steps to reproduce

The bug is a documentation issue, not a code issue
## Expected behavior

The documentation should more specifically describe that it tests searching for val in an array that doesn't have val
## Screenshots

N/A
## Environment

N/A

**Comment by skatcat31** [comment]
If you'd like to open a pull request we'd welcome it. Thanks for pointing this out!
