### ISSUE TITLE
Glossary Examples

### ISSUE THREAD

**Issue by skatcat31** [30-seconds/30-seconds-of-code#774]
## Description

With the glossary section we might want some documentation of edge cases or things to be aware of. While they don't have to be as complex as MDN, they should note some things, like coercion to instance for primitives.

We should however have a standard format for glossary terms that should have code examples, and those that do not

**Comment by Chalarangelo** [comment]
The template of 30interviews comes to mind. We could add a **Notes** subsection with bullet points adn only render/add it on snippets that require some kind of note below them. I suspect that any code will not be longer than a line or two, so we can probably get away with adding it in there.

**Comment by Chalarangelo** [comment]
@skatcat31 **Notes** or **Remarks** maybe?

**Comment by MrJY** [comment]
nice

**Comment by Chalarangelo** [comment]
I am closing this one due to inactivity. Glossary might end up in the graveyard sooner or later, as we practically built it and left it there to die, so this whole issue is kind of irrelevant for the long term.
