### ISSUE TITLE
[BUG] tomorrow.js is extremely difficult to read, and doesn't pass the tester

### ISSUE THREAD

**Issue by itchylol742** [30-seconds/30-seconds-of-code#775]
## Bug description 

tomorrow.js is extremely difficult to read, and doesn't pass the test

## Steps to reproduce

in tomorrow.js, the code is extremely difficult to understand
```js
const tomorrow = (long = false) => {
  let t = new Date();
  t.setDate(t.getDate() + 1);
  const ret = `${t.getFullYear()}-${String(t.getMonth() + 1).padStart(2, '0')}-${String(
    t.getDate()
  ).padStart(2, '0')}`;
  return !long ? ret : `${ret}T00:00:00`;
};
```
also, it doesn't pass tomorrow.test.js
```js
const t1 = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate() + 1);
const t2 = new Date(tomorrow());
// (other tests)
test('Returns the correct date', () => {
  expect(t1.getDate()).toBe(t2.getDate());
});
```

## Expected behavior

A more readable code, and passing the test.

## Screenshots

pastebin: https://pastebin.com/raw/vR5uK7qP (from testlog)

## Environment

Node 8.10.0
npm 6.4.1
Visual Studio Code 1.27.2
Windows 8.1

**Comment by gitjeff05** [comment]
Should this just use ``t.toLocaleDateString()`` rather than attempting to format for one specific locale? [The ``toLocaleDateString`` method also accepts a locale](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#Checking_for_support_for_locales_and_options_arguments):
```
const t = new Date()
console.log(t.toLocaleDateString()) // 10/5/2018
console.log(t.toLocaleDateString('de-DE')) // 5.10.2018
```

**Comment by skatcat31** [comment]
@gitjeff05 We want to hard code it at midnight local. It's to represent the first moment of tomorrow so you can try and use it to figure out when tomorrow starts. This is useful for countdowns and other such things that care about midnight(usually when tomorrow is defined)

**Comment by Chalarangelo** [comment]
Seeing as this thread is kind of dead, please move all further discussion to #849.
