### ISSUE TITLE
[FEATURE] Add sidebar menu to static pages.

### ISSUE THREAD

**Issue by bersLucas** [30-seconds/30-seconds-of-code#788]
## Bug description 

Static pages, (Archive.html, Contributing.html, glossary.html, ect) do not have the sidebar menu on the top left, a user is unable to navigate from these pages to another page.

## Expected behavior

Add `<button class="menu-button"></button>` to the static pages and have it have the same sidebar funcationality as the other pages.

## Screenshots

![screen shot 2018-10-03 at 9 45 11 am](https://user-images.githubusercontent.com/3892772/46414416-0d752880-c6f1-11e8-8219-e8fe4ce99e03.png)
![screen shot 2018-10-03 at 9 45 16 am](https://user-images.githubusercontent.com/3892772/46414417-0d752880-c6f1-11e8-85ed-4bbc59fb3cdf.png)

**Comment by Chalarangelo** [comment]
This is already planned, but we haven't had any time to implement it yet. I'll be working on it as soon as possible, along with a few other improvements for the website.

**Comment by SarathSantoshDamaraju** [comment]
@Chalarangelo ,
Can I take-up this?

**Comment by Chalarangelo** [comment]
With the help of @SarathSantoshDamaraju, only `about.html` and `contributing.html` don't have navigation yet.

**Comment by SarathSantoshDamaraju** [comment]
@Chalarangelo , Will work on them and raise a PR soon.

**Comment by flxwu** [comment]
Thanks for your contribution! @SarathSantoshDamaraju 🙂 ❤️
