### ISSUE TITLE
palindrome needs an update

### ISSUE THREAD

**Issue by skatcat31** [30-seconds/30-seconds-of-code#833]
## Bug description 

Not a bug, but still sloppy none the less.

## Steps to reproduce

Read `snippets/palindrome.md`. There should be a few mistakes(prototype methods not marked with #, spelling errors, etc.)

Sadly I don't have enough time to pour over it letter by letter(packing to leave town Sunday for an interview)

**Comment by mphan6** [comment]
Hello,

I've attempted to make the corrections in the attached PR, but I'm not sure what you're talking about in regards to the 'prototype methods not marked with #'.
If you wouldn't mind letting me know what you mean and if there's anything else you'd like me to update, I'd appreciate it!

Thanks,
Matt
