### ISSUE TITLE
Command-line application (CLI)

### ISSUE THREAD

**Issue by sQVe** [30-seconds/30-seconds-of-code#837]
My workflow is almost entirely around terminals and vim, so I've been missing a good and clean way to search and navigate your snippets. **I created a command-line application, [30s](https://github.com/sQVe/30s) to ease my itch**. The initial release is quite solid but I will be expanding on features when I find the time. I hope some of you will find it useful.

**Comment by Chalarangelo** [comment]
Added the CLI app in the README at the top, along with the rest of associated projects that provide functionality like this. Thanks for building this, I'm looking forward to seeing the CLI app grow and get new features! 👍
