### ISSUE TITLE
Simpler way to create the `filterNonUnique`

### ISSUE THREAD

**Issue by omriLugasi** [30-seconds/30-seconds-of-code#873]
## Description
The filterNonUnique array option is very nice but there is a simpler way to do it

Current 
----
`const filterNonUnique = arr => arr.filter(i => arr.indexOf(i) === arr.lastIndexOf(i))`

My suggestion
----
`const filterNonUnique = arr => [...new Set(arr)]`

Please let me know if you want a pull request :)

**Comment by skatcat31** [comment]
This is a newer way that is finally available. I would have no problem with it being PRed. Consensus?

**Comment by atomiks** [comment]
Seems like it already exists: [`uniqueElements`](https://github.com/30-seconds/30-seconds-of-code#uniqueelements)

So basically an alias for that one...

**Comment by Chalarangelo** [comment]
The two snippets are different. Take this test case for example:

```js
filterNonUnique([1, 2, 3, 4, 1, 1, 2]); // [3, 4]
uniqueElements([1, 2, 3, 4, 1, 1, 2]); // [1, 2, 3, 4]
```

`filterNonUnique` will remove every instance of each value that appears twice, while `uniqueElements` will only keep one of each value.

I'm closing on the basis that the proposed change alters the snippet functionality.
