### ISSUE TITLE
Module files incorrect

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-code#875]
- [`_30s.esm.js`](https://github.com/30-seconds/30-seconds-of-code/blob/240e800a33ab01b8c540a53cec76e4e11c415f19/dist/_30s.esm.js) is displaying `module.exports = { ...snippets }`, should be `export { ...snippets }`

- [`_30s.js`](https://github.com/30-seconds/30-seconds-of-code/blob/240e800a33ab01b8c540a53cec76e4e11c415f19/dist/_30s.js) no longer works in the browser (throws an error `module is not defined`)

It appears to be using [`require()` instead of ES6 import syntax](https://github.com/30-seconds/30-seconds-of-code/blob/master/scripts/module.js#L45), which Rollup uses

**Comment by Chalarangelo** [comment]
@atomiks you are the one who fixed them in the first place, can you update them yet again?

**Comment by atomiks** [comment]
Also we'll add `"sideEffects": false` to `package.json` to support webpack tree-shaking

**Comment by Chalarangelo** [comment]
Thanks for fixing it. I will release a patch tomorrow if I get the time to address this issue on npm.
