### ISSUE TITLE
Using regex for StripHTML not right

### ISSUE THREAD

**Issue by ilicmarko** [30-seconds/30-seconds-of-code#890]
## Bug description 
Using RegEx for stripping HTML/XML tags is not a good idea. Unfortunately, there isn't a good enough RegEx to select the HTML tags and not mix it up with regular text.

`<[^>]*>` this RegEx will fail if you have simple math inside your text `<` or `>`.

## Steps to reproduce
1. Make a simple HTML with math `<p>Did you know that JS < Python</p>`
2. Call `stripHTMLTags(ourHTML)`

## Expected behavior
We would expect to get the text only `Did you know that JS < Python` but that is not the case. Because of the RegEx, it will capture `< Python </p>` as one group.

## Solution
The best and right way to strip HTML is to use the DOM API.

```js
const stripHTMLTags = str => {
  const node = document.createElement('dummy')
  node.innerHTML = str
  return node.textContent || node.innerText || ''
}
```

**Comment by Chalarangelo** [comment]
Using the DOM API assumes that this snippet will be run in a browser, meaning that this cannot run on a server-side environment such as node.js.

Proper html code should have `<` in text escaped as `&lt;`.
