### ISSUE TITLE
npm scripts don't appear to update test/_30s.js

### ISSUE THREAD

**Issue by RobertAKARobin** [30-seconds/30-seconds-of-code#891]
## Description
I believe I followed contrib guidelines for #889, including running `npm run tagger`, `npm run tester`, and `npm run test`. However, my tests did not pass until I manually updated `test_30s.js`. Is one of the scripts supposed to update this file?

**Comment by Chalarangelo** [comment]
Yeah, I think the guidelines are a bit out of date. I think it's the `packager`'s job. I'll update them asap.

**Comment by Chalarangelo** [comment]
Resolved in bd11d03. Waiting for @fejes713 to update the image at the top and resolve #892 as well.
