### ISSUE TITLE
Image at top of contributing.md is not accurate

### ISSUE THREAD

**Issue by RobertAKARobin** [30-seconds/30-seconds-of-code#892]
![img](https://user-images.githubusercontent.com/6268177/49879946-b080a780-fdf0-11e8-94b9-6fab02e9b17a.png)

* Image references `npm run tdd` which is undefined
* Image doesn't reference `npm run tester`, but documentation does

**Comment by Chalarangelo** [comment]
Yep, this is outdated, too. I'm planning to rewrite this.

**Comment by Chalarangelo** [comment]
Resolved in 13905ed.
