### ISSUE TITLE
isEmpty will be invalid for Set and Map

### ISSUE THREAD

**Issue by fatedeity** [30-seconds/30-seconds-of-code#901]
## Bug description
Object.keys is invalid for Set and Map, If a Set object add a value, then use Object.keys will get a empty array, the same to Map.

**Comment by skatcat31** [comment]
also this works on functions, which... is that the right way to do things?

```js
isEmpty(() => null) // true
```

Maybe we should go with a mini library? Check if it's a primitive and if so return true, otherwise proceed onto tests for iterator, length, and then keys?

**Comment by haoliangwu** [comment]
maybe this repo should contain other specific type check util methods like `isMap`、`isSet` and etc. 

Then we can ensure `val` as Map/Set type by invoking `(isMap || isSet)` methods and check if its `size` property equal to zero without increasing time complexity.

**Comment by skatcat31** [comment]
@haoliangwu we decided against that a long time ago because we want each snippet to be able to be used on their own. This is why this one is kind of monster

**Comment by ektada** [comment]
i would like to work on the project

**Comment by skatcat31** [comment]
Maybe we just adapt this to a more generic "check property" snippet?

```js
const checkProp = (predicate, property) => obj => predicate(obj[property])
```

**Comment by skatcat31** [comment]
I keep forgetting to do this... After a long day at work I often just boot up a game now...

**Comment by skatcat31** [comment]
@Chalarangelo after checking the current state I'm going to close this. As it notes it checks for keys length or object property length it should be obvious this would not work on something this is defined empty by a size property. While some may not understand it, it means they aren't looking closely enough at the Map and Set types. Why Map and Set don't have lengths is beyond me... Either add a size to Arrays or keep it consistent TC39...

**Comment by GrosSacASac** [comment]
The current description is still 

> Returns true if the a value is an empty object, collection, **map or set**, has no enumerable properties or is any type that is not considered a collection.

The original reason Map and Set use size instead of length is for backwards compatibility, with old libraries that check for length

**Comment by skatcat31** [comment]
good catch. Will open PR

**Comment by skatcat31** [comment]
Opened PR to update language and remove Map and Set tests
