### ISSUE TITLE
deepClone transfer [] to 0

### ISSUE THREAD

**Issue by savoygu** [30-seconds/30-seconds-of-code#906]
## Screenshots

![image](https://user-images.githubusercontent.com/9302866/50898296-b72f2880-1449-11e9-98eb-a1fbf2f0dfdc.png)

```
const obj = []
const clone = Object.assign({}, obj)
(clone.length = obj.length) && Array.from(clone)

output: 0, not []
```

**Comment by Chalarangelo** [comment]
That is quite an interesting edge-case. We should look into it. Alternatively, you can submit a PR with a fix, if you want.
