### ISSUE TITLE
Search field.

### ISSUE THREAD

**Issue by AlekseyPn** [30-seconds/30-seconds-of-code#914]
Hi :)
## Bug description 
When I search something in your site and after I clear my search query, menu doesn't return to initial state.

## Steps to reproduce
1. Write search query, for example groupBy.
2. Clear search query.
3. Try to click by menu items.

## Expected behavior
Menu is return to initial state for search manually.

## Screenshots
Firefox
![image](https://user-images.githubusercontent.com/18575325/52110996-387e7300-2624-11e9-8a86-c16376b89c7e.png)
Chrome
![image](https://user-images.githubusercontent.com/18575325/52111027-51872400-2624-11e9-905a-d8e9a13456dc.png)

## Environment
Reproduce in Firefox and Chrome on last version.

**Comment by Chalarangelo** [comment]
I noticed this a couple of days ago, too. If you want to try fixing it, you are more than welcome to submit a PR.

**Comment by lenoraporter** [comment]
@Chalarangelo I am attempting to fix the problem, but I do not exactly understand where or which piece of code to edit. I see what's happening and I know how to fix it, but when I attempted to update the static-page-start and run yarn webber, my changes weren't reflected.

If you could point me in the right direction I would gladly help.

**Comment by Chalarangelo** [comment]
That's the correct way to do it. However, you should edit `page-start`, `static-page-start` and maybe even `beginner-page-start` if your changes affect code that is also present there. Also, bear in mind that you should only commit changes to those files and not the built output. Thanks for the effort, @lenoraporter.

**Comment by Chalarangelo** [comment]
Resolved in #928.
