### ISSUE TITLE
getURLParameters can be wrote in this way

### ISSUE THREAD

**Issue by RobinZhao00** [30-seconds/30-seconds-of-code#915]
const getURLParameters = url => (url.match(/([^?=&]+)(=([^&]*))/g) || [])
  .filter(a => a.includes('='))
  .map(b => b.split('='))
  .reduce((prev, curr) => ({ ...prev, [curr[0]]: curr[1] }), {});

getURLParameters wrote in this way can be easily understood

**Comment by skatcat31** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/UR

If anything we should just rewrite getURLParameters using the URL class.

```js
const getURLParameters = url => new URL(url).search.slice(1).split('=').reduce((acc, [key, value]) => key && (acc[key] = value, acc), {})
```

**Comment by RobinZhao00** [comment]
![image](https://user-images.githubusercontent.com/19774093/52160848-700a1f80-26f7-11e9-804c-88557e207be0.png)

**Comment by RobinZhao00** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/UR
> 
> If anything we should just rewrite getURLParameters using the URL class and avoid the regex.
> 
> ```js
> const getURLParameters = url => new URL(url).search
>   .slice(1)
>   .split('=')
>   .reduce((acc, [key, value]) => key && (acc[key] = value, acc) || acc, {})
> ```

![image](https://user-images.githubusercontent.com/19774093/52160851-97f98300-26f7-11e9-84f5-3a1d7d84d2e8.png)

**Comment by RobinZhao00** [comment]
> > https://developer.mozilla.org/en-US/docs/Web/API/UR
> > If anything we should just rewrite getURLParameters using the URL class and avoid the regex.
> > ```js
> > const getURLParameters = url => new URL(url).search
> >   .slice(1)
> >   .split('=')
> >   .reduce((acc, [key, value]) => key && (acc[key] = value, acc) || acc, {})
> > ```
> 
> ![image](https://user-images.githubusercontent.com/19774093/52160851-97f98300-26f7-11e9-84f5-3a1d7d84d2e8.png)

```javascript
const getURLParameters = url => new URL(url)
      .search.slice(1)
      .split('&')
      .map(itm => itm.split('='))
      .reduce((prev,[ key, value]) => ({ ...prev, [key]: value}), {});
```

**Comment by RobinZhao00** [comment]
> URL class and avoid the regex
 A summary :
```javascript 
// 通过创建URL对象获取查询参数
// get search by URL class
const getURLParameters = url => new URL(url).search
  .slice(1)
  .split('&')
  .map(itm => itm.split('='))
  .reduce((prev, [key, value]) => ({ ...prev, [key]: value }), {});

// 通过正则获取查询参数
// get search by regex
const getURLParameters = url => (url.match(/([^?=&]+)(=([^&]*))/g) || [])
  .filter(a => a.includes('='))
  .map(b => b.split('='))
  .reduce((prev, [key, value]) => ({ ...prev, [key]: value }), {});
```

**Comment by Chalarangelo** [comment]
Based on [this perf](https://jsperf.com/geturlparams-915), the existing version performs better than the suggested change both on Chrome and Firefox. Therefore, I am closing the issue as the readability improvements to the snippet are negligible.

**Comment by skatcat31** [comment]
@Chalarangelo https://nodejs.org/docs/latest-v4.x/api/url.html#url_url and if you scroll down search is available

**Comment by skatcat31** [comment]
I did however manage to delete the part that made it actually work in an edit... go me -.-

```js
const getURLParameters = url => new URL(url).search
  .slice(1)
  .split('&')
  .map(s =>s.split('='))
  .reduce((acc, [key, value]) => key && (acc[key] = value, acc) || acc, {})
```
