### ISSUE TITLE
Language contamination

### ISSUE THREAD

**Issue by paulcanning** [30-seconds/30-seconds-of-code#917]
I only have PHP selected, but I get cards like this

[https://imgur.com/a/d6p7TaC](https://imgur.com/a/d6p7TaC)

Which is Python(?)

**Comment by flxwu** [comment]
Hey, thank you for your issue. Unfortunately, we don't have anything to do with wither 30-seconds-of-knowledge or 30-seconds-of-php.

**Comment by lybPigff** [comment]
> Hey, thank you for your issue. Unfortunately, we don't have anything to do with either 30-seconds-of-knowledge or 30-seconds-of-php.

How about JavaScript or node.js?

**Comment by peni86** [comment]
Jaringan akurat
