### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by MacFlurry** [30-seconds/30-seconds-of-code#921]
Hello,

Do you plan to port 30 sec of code to safari ?
A thousands of people don't use chrome.

Thanks,

**Comment by Chalarangelo** [comment]
All snippets are written in ES6 and are not browser-specific. Same goes for the website and README - everything has been tested on all browsers, not just Chrome.

**Comment by MacFlurry** [comment]
I don't see a safari extension though

**Comment by Chalarangelo** [comment]
The extension is another project, not officially supported, although endorsed, by the 30 seconds team.
Please ask about it in [30 seconds of knowledge](https://github.com/petrovicstefanrs/30_seconds_of_knowledge).
