### ISSUE TITLE
spam issues

### ISSUE THREAD

**Issue by vgrafe** [30-seconds/30-seconds-of-code#925]
Hi, 

I am receiving emails on my work inbox (vincent.grafe@curiositystream.com) for this whole repo. Every issue filed, answered, PR, commit... everything lands in my inbox. It is driving me crazy.

I did never watch or star the repo. It started happening out of the blue.

My Github account does not even use this email as login. I have no idea on how and why this is happening.

Thank you for helping on this.

edit: clicking on the "unsubscribe" link of the email brings me to this repo, with that error.

![screen shot 2019-02-23 at 10 17 53 am](https://user-images.githubusercontent.com/3950855/53288286-b67df780-3754-11e9-9f3c-6089f9bed6b7.jpg)

**Comment by YusofBandar** [comment]
I don't know if this would help but have you checked out this article on notifications:

https://help.github.com/en/articles/subscribing-to-and-unsubscribing-from-notifications

**Comment by vgrafe** [comment]
I am getting notifications for everything under this repo, without opting in notifications. I'll contact github, but I'd like to know: is there anything set on your org, like a mailing list or something like that?

**Comment by YusofBandar** [comment]
I am not the owner of this repo so i can't say for sure, but I suspect there isn't.

When ever I get an email from Github there is always a unsubscribe link, have you tried that.

**Comment by vgrafe** [comment]
This is part of the issue description. The link does not work. The email address I am getting spammed at is not even my github email.

**Comment by Chalarangelo** [comment]
Yep, this is not an issue with the repo or the org. We are not sending emails to people about anything we do, let alone issues and PRs. It's probably an issue with Github or a 3rd-party app. Hope you can resolve this.

I'll keep this open for a little bit, post any information you get here and inform us if we can help in any way with this if it's some kind of configuration problem.

**Comment by vgrafe** [comment]
Sounds good. I already contacted github's support... crossing fingers. Thank you!

**Comment by vgrafe** [comment]
I'll close - it seems to be redirects from a former employee's email address. Thank you!
