### ISSUE TITLE
differenceBy doesn't transform values then check the difference.

### ISSUE THREAD

**Issue by benschac** [30-seconds/30-seconds-of-code#930]
## Bug description 

differenceBy should apply the function, then check the difference and return the transformed | applied difference value. Currently, it will not transform the element if it's a difference.

## Steps to reproduce
Run the function

## Expected behavior

should apply the function to all elements, then check the difference and return the transformed | applied difference value.

**Comment by Chalarangelo** [comment]
I see what you mean and it's probably the correct implementation. Not sure how we missed that. However, your PR should only alter the snippet file and/or tests if necessary, so please submit a new one following these rules. Thanks for your time and bringing this issue up!

**Comment by benschac** [comment]
Happy to help!

For sure.

Curious, should I submit a PR for [contributing](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md)? I followed the steps on there, totally makes sense that you'd want Travis to run those npm scripts.
