### ISSUE TITLE
isNumber is wrong for NaN

### ISSUE THREAD

**Issue by mkopa** [30-seconds/30-seconds-of-code#935]
## Bug description
NaN is not a number, but isNumber(NaN) returns true.

My suggest is:
`const isNumber = val => typeof val === 'number' && !isNaN(val);`

**Comment by jjeejj** [comment]
@mkopa you can use `Number.isNaN` function

**Comment by mkopa** [comment]
@jjeejj What do you mean `I can use Number.isNaN?`
I'm writing about https://github.com/30-seconds/30-seconds-of-code#isnumber when function `isNumber` return `true` for `NaN` value.

**Comment by jjeejj** [comment]
@mkopa yes,you are right ,but i think  the `Number.isNaN`  function is better than the `isNaN`， because `isNaN('ss')` return `true`

**Comment by mkopa** [comment]
@jjeejj you are right, but in this case it's doesn't matter because `typeof 'ss' === 'string'`, not `'number'`

**Comment by jjeejj** [comment]
@mkopa you can consider it conveniently through performance

**Comment by mkopa** [comment]
Maybe better solution will be:
`const isNumber = val => typeof val === 'number' && val === val`
because NaN is never equal to NaN?

**Comment by jjeejj** [comment]
> Maybe better solution will be:
> `const isNumber = val => typeof val === 'number' && val === val`
> because NaN is never equal to NaN?

Yes, This solution is better.

**Comment by Chalarangelo** [comment]
I agree that the below is probably the optimal solution as it is a good place to explain how `NaN` self-equality works.

```js
const isNumber = val => typeof val === 'number' && val === val;
```

I would love to see a PR for this, it's a pretty important consideration. Additional tests to deal with the edge cases would be appreciated, too.
