### ISSUE TITLE
[SUGGESTION] Implementing live-code playground snippets on examples 

### ISSUE THREAD

**Issue by musyilmaz** [30-seconds/30-seconds-of-code#936]
## Description 

As a react / electron developer, I am using the plugin since sawing it on product hunt I think. Thanks for the effort. (edited: seems like plugin is somewhat older than recent product hunt appear)
Mainly for the react snippets utilizing a codepen, condesandbox example could be amazing. Do you guys interested in the case? This could help on frontend examples definitely, due to seeing the code snippet live is an amazing method to grasp the subject.

If so, I could append a small codepen like instance inside one of the examples.

**Comment by YusofBandar** [comment]
Its definitely an interesting idea but i feel it defeats the whole point of the repo. All code snippets take 30 seconds to understand thus a live code snippet is not needed.

However may be for the more advanced snippets, it could be useful.

**Comment by Chalarangelo** [comment]
I would like to eventually implement a generated link for each snippet that links to a repl or pen - not embedded, but external links. However, that is probably a couple of months away, as the website should be getting a facelift before implementing new features. So, hang in there or send us a PR that moves in the right direction if you want to help out!

**Comment by madarsbiss** [comment]
I would agree with @YusofBandar on this.. Each snippet is easy to understand and if a user needs some in-depth exploring, he might go to mdn for full documentation!

**Comment by skatcat31** [comment]
@Chalarangelo the Ramda repo has a great repl that should be easy to lift and has a way to link to it too that they use. The Ramda site is pretty great. BTW have I mentioned I like Ramda a billion times yet?

**Comment by fejes713** [comment]
Haha @skatcat31 yes you did. Yes, Rambda's website looks all right - I am not a huge fan of the design but the functionality is great. I really like the ability to see function params clearly defined. 

While it seems like a nice addition some of their features would require us to completely change the structure of our snippets + add some additional data.

I do like this idea for embedding links to external JS bin or something. Sounds like a cool way to start building something your own out of our functions.

**Comment by Chalarangelo** [comment]
I want to move on this one now that the new website is live. I will investigate in the coming weeks and report back.

**Comment by Chalarangelo** [comment]
Been a long time since this was opened, we have tried a few things and it feels like it's not something that's absolutely necessary for the user experience. Snippets that really require a playground, like React snippets, get one, while the simpler ones (JS, Python, PHP) get a copy button. I'm closing this topic, as this is our current decision in terms of implementation for multiple reasons.
