### ISSUE TITLE
Silent type cast not mentioned

### ISSUE THREAD

**Issue by GrosSacASac** [30-seconds/30-seconds-of-code#951]
For mapObject

the keys will be cast to String, it should be explained, or at least a warning. The example makes it look like they are stored as numbers.

**Comment by skatcat31** [comment]
I'm confused on where it looks like they would be stored as numbers versus string coercion?

**Comment by fejes713** [comment]
@GrosSacASac could you please provide more details regarding this issue?

If this is what bothers you I don't see any problems with it. The output from the 30seconds docs matches the output on the `console`. While Object `keys` are indeed **only** strings their properties could be accessed with numbers too. 

<img width="732" alt="Screen Shot 2019-04-20 at 5 49 11 PM" src="https://user-images.githubusercontent.com/25749162/56459501-e2081180-6394-11e9-95b7-ec33fd669f74.png">

JavaScript Engines do perform something called _type coercion_ when trying to access object keys with values other than type String or Symbol. For further info, see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors#Property_names).

**Comment by fejes713** [comment]
Hopefully, this helped a bit, if not let's solve this one together 😄

**Comment by GrosSacASac** [comment]
> where the key-value pairs consist of the **original value** as the key and the mapped value

I would write:
 where the key-value pairs consist of the **stringified value** as the key and the mapped value

**Comment by fejes713** [comment]
Thanks for clarifying this. @skatcat31 this seems like a solid change - should I modify the function docs?

**Comment by skatcat31** [comment]
It's a fair clarification for newer programmers(I've met more than a few who think object literals are Maps)

**Comment by vikash-driod** [comment]
kuehgflidsnflksdjf;sdfms
