### ISSUE TITLE
isPlainObject does not work with prototype less objects

### ISSUE THREAD

**Issue by GrosSacASac** [30-seconds/30-seconds-of-code#953]
## Steps to reproduce
isPlainObject(Object.create(null)); // false

## Expected behavior
isPlainObject(Object.create(null)); // true

**Comment by skatcat31** [comment]
a Plain Object is defined as an object that has been created using the Object literal syntax or `new Object()`(Plain Old JavaScript Object).

Object.create(prototype) is not considered to use the Object literal or new Object() syntax, and thus is not a Plain Object
