### ISSUE TITLE
is merge behavior correct?

### ISSUE THREAD

**Issue by zslucky** [30-seconds/30-seconds-of-code#957]
Refer the testing code.
![1555661611077](https://user-images.githubusercontent.com/15725589/56415118-51133680-62bf-11e9-8bd9-1b68395f5b29.jpg)

Is this behivor correct?

In my mind, looks like it should be deep merge every object, and return a merged object, not array

**Comment by zslucky** [comment]
I'm not sure is this as designed?

**Comment by fejes713** [comment]
Hey @zslucky! Thanks for mentioning this. 👍 

While it may seem weird at first I think this is how it's supposed to be. Lodash has a very similar method as well and their outputs are the same. 

You can see more examples at their [docs](https://lodash.com/docs/4.17.11#merge)

Hopefully, this helps 😃

**Comment by zslucky** [comment]
@fejes713 Thanks, lodash `merge` is similar but not the same, lodash object merge are different, it's deep merge. not only concat into an array.

**Comment by fejes713** [comment]
Thanks for clarifying that @zslucky 👍 

@skatcat31 @Chalarangelo what do you think? Worth reopening the issue?
