### ISSUE TITLE
about equals function

### ISSUE THREAD

**Issue by USTC-Han** [30-seconds/30-seconds-of-code#958]
## Description

![image](https://user-images.githubusercontent.com/38212028/56859440-96212200-69bd-11e9-84ea-74faf99d1f4b.png)
1、I think the fifth line of code is meaningless.Because if  a is undefined or null ,!a will be true and the code will execute the forth line.  The fifth line will never be executed
2、when a is 0 and b is -0 ,it will return true, but Object.is(0,-0) will return false.

**Comment by USTC-Han** [comment]
Another question: if I execute equals(new Date(),12),it will return ture.
If I fix Object.prototype to Object.__proto__ ,the code will return false.

**Comment by Chalarangelo** [comment]
Closing due to inactvity and the snippet having the correct behavior and implementation as-is.
